---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "${APP}-gatus-ep"
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: "${APP}"
        group: internal
        url: "https://${GATUS_SUBDOMAIN:-${APP}}.${SECRET_DOMAIN}"
        interval: 1m
        ui:
          hide-hostname: true
          hide-url: true
        conditions:
          - "[STATUS] < 300"
          - "[RESPONSE_TIME] < 300"
        alerts:
          - type: pushover