---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app homebridge
spec:
  interval: 12h
  maxHistory: 3
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    crds: Create
    replace: true
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
    controllers:
      homebridge:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/homebridge/homebridge
              tag: 2024-10-02@sha256:5ec50d9a0f2a41668ec33be82f081dd2886471f490d03e56e80bdd639bb4a7df
            env:
              TZ: America/New_York
              ENABLE_AVAHI: "1"
              PGID: 1000
              PUID: 1000
              HOMEBRIDGE_CONFIG_UI: 1
              HOMEBRIDGE_CONFIG_UI_PORT: &port 8888
            # securityContext:
            #   allowPrivilegeEscalation: false
            #   capabilities:
            #     drop:
            #       - ALL
        # pod:
        #   securityContext:
        #     runAsNonRoot: true
        #     runAsUser: 568
        #     runAsGroup: 568
        #     fsGroup: 568
        #     fsGroupChangePolicy: OnRootMismatch
        #     seccompProfile:
        #       type: RuntimeDefault
    service:
      app:
        controller: homebridge
        ports:
          http:
            port: *port
      bridge:
        enabled: true
        controller: homebridge
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 10.20.0.157
        ports:
          bridge:
            enabled: true
            port: 51986
            targetPort: 51986
            protocol: TCP
    persistence:
      homebridge:
        enabled: true
        existingClaim: homebridge

    ingress:
      app:
        enabled: true
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
        hosts:
          - host: &host "homebridge-k8s.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
