---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homebridge
  namespace: services
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: synology-csi-retain
  resources:
    requests:
      storage: 1Gi