---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
components:
  - ../../components/namespace
resources:
  - ./cilium/ks.yaml
  - ./coredns/ks.yaml
  - ./local-path-provisioner/ks.yaml
  - ./metrics-server/ks.yaml
  - ./reloader/ks.yaml
  - ./snapshot-controller/ks.yaml
  - ./external-secrets/ks.yaml
  - ./synology-csi/ks.yaml
  - ./headlamp/ks.yaml
