---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: headlamp
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: headlamp-secret
    template:
      engineVersion: v2
      data:
        clientID: "{{ .HEADLAMP_CONFIG_OIDC_CLIENT_ID }}"
        OIDC_CLIENT_ID: "{{ .HEADLAMP_CONFIG_OIDC_CLIENT_ID }}"
        clientSecret: "{{ .HEADLAMP_CONFIG_OIDC_CLIENT_SECRET }}"
        OIDC_CLIENT_SECRET: "{{ .HEADLAMP_CONFIG_OIDC_CLIENT_SECRET }}"
        issuerURL: "{{ .HEADLAMP_CONFIG_OIDC_IDP_ISSUER_URL }}"
        OIDC_ISSUER_URL: "{{ .HEADLAMP_CONFIG_OIDC_IDP_ISSUER_URL }}"
        OIDC_SCOPES: "{{ .HEADLAMP_CONFIG_OAUTH_SCOPES }}"

  dataFrom:
    - extract:
        key: headlamp
