---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
spec:
  interval: 30m
  chart:
    spec:
      chart: headlamp
      version: 0.27.0
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    config:
      oidc:
        externalSecret:
          enabled: true
          name: headlamp-secret
    ingress:
      enabled: true
      ingressClassName: internal
      annotations:
          external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
      hosts:
        - host: &host headlamp.${SECRET_DOMAIN}
          paths:
            - path: /
              type: Prefix
      tls:
        - hosts:
          - *host

