---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gatus-dns-config
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: gatus-dns-config-secret
    creationPolicy: Owner
    metadata:
      labels:
        gatus.io/enabled: "true"
    template:
      templateFrom:
        - configMap:
            name: gatus-external-service-tpl
            items:
              - key: config.yaml
  dataFrom:
    - extract:
        key: pihole