---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: airtail
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: airtrail-secret
    template:
      engineVersion: v2
      data:
        DB_URL: |-
          postgres://{{ .AIRTRAIL_POSTGRES_USER }}:{{ .AIRTRAIL_POSTGRES_PASS }}@postgres16-rw.database.svc.cluster.local/airtrail
        INIT_POSTGRES_DBNAME: airtail
        INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .AIRTRAIL_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .AIRTRAIL_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        DB_PASSWORD: "{{ .AIRTRAIL_POSTGRES_PASS }}"
        DB_DATABASE_NAME: airtrail
        DB_USERNAME: "{{ .AIRTRAIL_POSTGRES_USER }}"
  dataFrom:
    - extract:
        key: airtrail
    - extract:
        key: cloudnative-pg