---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: rocketchat
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/rschoebel/helm-charts
  ref:
    branch: patch-1
  ignore: |
    # exclude all
    /*
    # include kubernetes directory
    !/rocketchat
