---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-nfs
  namespace: storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: synology-csi-iscsi-retain
  resources:
    requests:
      storage: 500Gi