ansible_become_pass: ENC[AES256_GCM,data:tQkwlJviOXQ701Oa0trlVQ==,iv:rn/RWcEDxXiaJqGCaP0zqf4yoSuhPxIShaWVkvK6EnM=,tag:lUOAcasDMvYSbLTeXPDpxw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxf6lyfrga0ddxltfhtgzvjkvq74yqjypcwxujpvh4grxp30u33su8s52d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxWjlKenlSTVpHOXN2OHpQ
            Y3BsaXlQQ3RiaXY5SFp5WE9rTXZ6dFJ3eXlNCnhLeW44M3BsMlZkTmFkbTFYcENN
            dm1PeDVXWlhudDBrREVVYUE2cGc5NFkKLS0tIFJsa2h3MllSK3ZobTNRVkFaTnY2
            cGtiQkE5YnJiNFl2dGlEMVk5dnYxQmMKnNj7BqvaZUhYCsAEpgP/JCCOxrnIXSIH
            PqACXourGNos40KLFkIB48a4q5OqPfi7KMd6SWQl7uFbAazbTHInjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-02T01:20:30Z"
    mac: ENC[AES256_GCM,data:M02ihf8UoIfF1MQjFe1vQNjNdbuYBOSPUEZcZATahNPBMRG7McBJSCMQdtAc18w8P5gUvgE2XBYx3cITeZLH4fHj/Ir5G9IBXPnzqfNZT5dGhwu/iN5O8W/gV8e9cayXi6TcFQ6hSL2euM4nyHZYp669uEtZzN30FcNc8cemS30=,iv:FatUU2uq3ekB86pa3G+U40bhu5G8B9rcTUNOaqYnm7k=,tag:KZ5kjBJSlolR9fCI927odg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
