ansible_become_pass: ENC[AES256_GCM,data:ykSIuC5mFGA710QkoRoEdg==,iv:WypQ8UnMmisSLvIqD9+U4PruVpCQSLftwnYBmUASvic=,tag:c9vQmFeoRJt9yy+fylGmaw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxf6lyfrga0ddxltfhtgzvjkvq74yqjypcwxujpvh4grxp30u33su8s52d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiOERTa3NZNmJ3Qm1NOGdH
            RHFoUGRMUkYxOWVra1pRMklncHdWSW9ScUVnClhhZ0cxUzRNRWZDZUJCUCtrSEdN
            T0pnejhnUVMxUCsvRkRiOFZrNVhPMHcKLS0tIEFoZXI3SUt5QTVYc3JvM2tDaXIr
            cE5lTllNNnlKNzBxdWhXMXh1MkF5RkUKEkbKDSTKcgkRt6iHoISs0prly+30cYD2
            B1Jg+rcR4/V7FFEPLFTjPG+H11NdQ150Mki9CSW6yejXQOKlgx8m8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-02T04:10:40Z"
    mac: ENC[AES256_GCM,data:8sSKKOhGT95QMK7GM+/+3IrUsrpSdHhjAdnP7zotofo0C06VdNSHGlHuHJlvOVU+aETQ03nbDCS7ThSGU7DmMQURRU5e45S/D7qppYGqo2zvqPgLwU9xaMOdOX87G5j2LC4pf5CamvrlBBEe21JRzNCvcTyuQMzgdpB33tXv2Bw=,iv:SHdkcDZ2Lqp225pBzNDG39Yd9V25kvhs2om+NPATyk0=,tag:yIZso7tOPhHe1XbtuKnPKg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
