ansible_become_pass: ENC[AES256_GCM,data:4yLSWc/R8hSGTjNGYeduVQ==,iv:P7GSj/cejHFZfh+rlR2DZi+OAWteUKyTEiqnBeb8nnU=,tag:JIju7pctBIZK8aBcbFa6vA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxf6lyfrga0ddxltfhtgzvjkvq74yqjypcwxujpvh4grxp30u33su8s52d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNjMwWGdxRXFSUE02MFBh
            bmoxdGJuMGpZU0NBL1VqcmZJMGN6eXVVZnpVCjljWjlvMXA0OXVYSVpFOGZiNHNN
            RDVkYkthYW9DMm9Sb1I1M3V5TE11c28KLS0tIFc5aVBrckZXNC9wT0Y0Mi9YQmVL
            ZW53YzZlVXMvS1MxUENoVi94U2xTZDgK2j4dxCalIODLrr7V64kv4dNMa5uuWU4N
            Qrvele2tygYLoLGSix+B7gKU6JRYMd9UVjZrMYYcNiAIeQMzqLO/zQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-30T21:19:33Z"
    mac: ENC[AES256_GCM,data:8qTRSTE4OlI4GAYdNcWOgh/8DLTxKFUE+NJYeT+qbDP6YwolwTMCK2cmWTBnHnhVeLsa0/VJob7hYutvzdF8554i8n/7wyQQRXAuzYuXZ21DT5OeBrBEJF0ydAcWzxTCFkpeQRPiEEbHygEKMmq+0CS0Mlnow9P+qDXaoLdQ1Ms=,iv:1AKNBbZEAN9mv/SoQ4mgqdu5q0iNmHAbIjLf8EOd9AA=,tag:CnIMDF8R/Nv3npgmBIqfNA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
