---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./backube.yaml
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./coredns.yaml
  - ./csi-driver-nfs.yaml
  - ./external-dns.yaml
  - ./external-secrets.yaml
  - ./grafana.yaml
  - ./ingress-nginx.yaml
  - ./jetstack.yaml
  - ./k8s-gateway.yaml
  - ./metrics-server.yaml
  - ./piraeus.yaml
  - ./prometheus-community.yaml
  - ./onepassword.yaml
  - ./stakater.yaml
  - ./synology-csi.yaml
  - ./weave-gitops.yaml
  - ./pihole.yaml
  # - ./headlamp.yaml
  # - ./cloudnative-pg.yaml
