---
global:
  resolve_timeout: 5m
route:
  group_by: ["alertname", "job"]
  group_interval: 10m
  group_wait: 1m
  receiver: email
  repeat_interval: 12h
  routes:
    - receiver: "null"
      match:
        alertname: Watchdog
    - receiver: "null"
      matchers:
        - alertname =~ "InfoInhibitor"
    - receiver: "email"
      continue: true
      matchers:
        - severity = "critical"
    - receiver: "null"
      matchers:
        - alertname = "etcdHighCommitDurations"
        - severity = "warning"
inhibit_rules:
  - equal: ["alertname", "namespace"]
    source_matchers:
      - severity = "critical"
    target_matchers:
      - severity = "warning"
receivers:
  - name: "null"
  - name: "email"
    email_configs:
      - send_resolved: true
        to: "{{ .ALERT_MANAGER_TO_EMAIL }}"
        from: "{{ .ALERT_MANAGER_FROM_EMAIL }}"
        smarthost: smtp-relay.default.svc.cluster.local:25
        hello: "Alert Manager"
        require_tls: false
        html: |-
          {{ "{{-" }} range .Alerts {{ "}}" }}
            {{ "{{-" }} if ne .Annotations.description "" {{ "}}" }}
              {{ "{{" }} .Annotations.description {{ "}}" }}
            {{ "{{-" }} else if ne .Annotations.summary "" {{ "}}" }}
              {{ "{{" }} .Annotations.summary {{ "}}" }}
            {{ "{{-" }} else if ne .Annotations.message "" {{ "}}" }}
              {{ "{{" }} .Annotations.message {{ "}}" }}
            {{ "{{-" }} else {{ "}}" }}
              Alert description not available
            {{ "{{-" }} end {{ "}}" }}
            {{ "{{-" }} if gt (len .Labels.SortedPairs) 0 {{ "}}" }}
              <small>
              {{ "{{-" }} range .Labels.SortedPairs {{ "}}" }}
                <b>{{ "{{" }} .Name {{ "}}" }}:</b> {{ "{{" }} .Value {{ "}}" }}
              {{ "{{-" }} end {{ "}}" }}
              </small>
            {{ "{{-" }} end {{ "}}" }}
          {{ "{{-" }} end {{ "}}" }}
