apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-password: ENC[AES256_GCM,data:DBAGZpFKsmrsos9h0FbXeItQbWk=,iv:MOOSlErEB8uaAnybH04ZcJASFRQaEN5ejIRZzGkui9g=,tag:+sGQS0bB8OUJ6I7TNZhtZg==,type:str]
    admin-user: ENC[AES256_GCM,data:BoWZ4jc=,iv:A8XColQ/S/MUpn8ark2Quhg9d4Lcmpc/cViu41oTb+Y=,tag:GxOd22XMuOF43fLF4uuu8A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxf6lyfrga0ddxltfhtgzvjkvq74yqjypcwxujpvh4grxp30u33su8s52d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5TzJVL3NvaTI1ZWN1NEJt
            eEtJWDZjdStoZ2hhdzgrRENXNG11K2tNQXcwCnM2WlQrOHMvLzNqbmFOY2NuMlgr
            T05jM2NYcDVaaXdOV3lKeEZYaE1hdDgKLS0tIGI1NUIwYWdVdUJDTjhXbkFwcklD
            U2FYMDh0aVhLVVNiYmNjNHFCRXVKS3MKqioPuH99tubSO6bqrBwvCv9i48I2HbKP
            bIq6bhSQ0LpVG0kpo3bLKihGrKLpK4MzODiVgjAIL0SS7c8i1N7MNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-02T02:53:10Z"
    mac: ENC[AES256_GCM,data:8FZ1/ABqY5hwLTaMLeMSxO5uy5Lqx/MrcswWBXlhwFUr9+TwzRRn6wWLhHo3itZWhSjLpvNngChBFN6vgO/vEFwCICEmqhG2j+LAqO8/5Q6C3gtlgg+VA2JnZ4FY56yr45uL4E+6yv9njsH5XkpZN7Mmr8PVE40e76aroxWyUaE=,iv:IJ0iZ7cFX5yRbxLofzlIO3zRmjtQgeJ5VgxRI/OThrw=,tag:NBaip8Fo1XhIcdjEUtv8ZA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
