apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-password: ENC[AES256_GCM,data:AGAxH9gM6MjUIYhHQa3d7/hLGpw=,iv:cPozeTCQjUeU/1y8paqvqagH3Z8r5TNgd++HYKqb3RE=,tag:6s3d3IoWcbkjwSoY235UPg==,type:str]
    admin-user: ENC[AES256_GCM,data:W9o9LEA=,iv:IJCTxswYqmET/NrIfB5nnQUvvEC5qcLJPLxC3yjKrpk=,tag:gNUpfiLH7/C35kiJaNy3+A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxf6lyfrga0ddxltfhtgzvjkvq74yqjypcwxujpvh4grxp30u33su8s52d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCZUlCelprNEFLRWdVNGF0
            WkNEUUlqbzVRWnc3ZVdkZW9vNVpXeTY3bm5NCmphcHU0OFcwQ0hEVE5LcGV6K2pi
            dWpGWEl0RmE1bXQ4NGgvWmRSN2ZNVHcKLS0tIFpVenl6Qjk4QlZxbE93bEhhUUtQ
            UHBRQlhRMllhQ1lsaWJodFJydVdId1EKrzo9Z1GBbuxAPh5Y98LLCr08ibEYtQSS
            coDZDiv1vUiT0O3YpNoWs+9O3GV4LrCJ/ynTvEBrHFsI4+3GuZxIig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-07T16:56:06Z"
    mac: ENC[AES256_GCM,data:caTglF3DNG77721f7P+t7UCR9dYB7elRgftJ+kc6U9V0uYOin8PMk7rCa01uBOG5VOMLFQZn9lRAz9rFSowwETFxdHZUFqN3rX0Qss+VSCXb6f6AvmQzBnNguWKKutFLJgxw6tSxwOVQ7vZL295AA+tYqj8CVEVJP0+fSmeLu9c=,iv:GY2M0DZBTOVQLkmAdODX4GyQshXwPu4j0yAwTub+cr4=,tag:X1j/R7o0Gn1Sv3/bIvROmQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
