apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-password: ENC[AES256_GCM,data:w7CS8RgIkLh4RmvcSsYN4nZCNC4=,iv:l4wZuE2weHwmH868eNYcjInwATAs6kNMsVzHbyOEBe8=,tag:wsts+X1QcvfQvevJwA8M2Q==,type:str]
    admin-user: ENC[AES256_GCM,data:0qUAeyU=,iv:O4Pn8bu2p7Bvmud8257fLs5bKjLvPfg+RfMoNLJcRGc=,tag:/O+BNySTQYijx/5ppUrg2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxf6lyfrga0ddxltfhtgzvjkvq74yqjypcwxujpvh4grxp30u33su8s52d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxU0M5YWRGM2I0eGNYZWQ0
            UjVFYnNzZUJNQUNWWDI0MCt6TWkrSTdtTW44CklSVDZ1cC9CZitvUVd1ZE53a0l0
            QndCTnlPVVUxcnBIYi9BKzNacTY4b2MKLS0tIFJBV3NGVHNRczFIZU1aMGhRZWtX
            TWFpeUJseW95dGxmYThpblVSVXBWcHMKJVMmk/OwE+pL3Du0V//Wm+1tnU3zkDEL
            ekqnCK1KZiFGxVqCBLp1MF4igW8s14XZOAFWHTFnMzheBBjW7Xw+iA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-30T01:30:41Z"
    mac: ENC[AES256_GCM,data:ni2oyNzwBxLGVWnfOSHmaW3knboWniBpvWbTNyV/KjrqY5JwvaFp6e0fTUfbiAweOQv+slsiEVo8Vc6Le0NWkejgQWqPdNHKGC+SzzrNOfM/EuacOacjRxSLsYvV3bc1cSv5HMdPFQICpQYjkIBHVau9MuYr9TLamz/YqlD8ZMk=,iv:6OxDzTNDYF3Fmi2gzQ4OT17Rq5H4foSDzyYyw/VZHhg=,tag:wCBBkpAMcOdCWf6j5zA+cQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
