apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-password: ENC[AES256_GCM,data:OlvyByv1T6QUsHySyjhcVnkrobo=,iv:FI1RvcY8rZExq7YTUmqDkdUJLnZRpgzRgEXz+WjUEQI=,tag:BHYyzYos81GUpeXca6P5BA==,type:str]
    admin-user: ENC[AES256_GCM,data:AM2ps4I=,iv:+pfmMI8lB4fbDfSzzKCykGWXmAOFK0v1WSzhPiPmTbQ=,tag:UcDKtkOpPv56nJiupKhOMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxf6lyfrga0ddxltfhtgzvjkvq74yqjypcwxujpvh4grxp30u33su8s52d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLS1VZQlJhNlpsemp2Z3Nz
            QURUcHFZYm1wdDJneFFVN1VzTnNPUmlrQTFZCkNjY1BXMmxGRjJSalRMem1Zdjkv
            UTUySnpuSWViVllFVkZMZ01QR1ZDT1UKLS0tIEdBOHhFcFk1bjJhN0lvcmovYWN5
            MzFrTUtXTVlKYU55T3JQQ3ZnRW9JdWsKgApk1xeVRUA0+Nr2AmynFU3ypkXDCBYt
            5aMZXkh/Y5mvDvhwxgED0V7ltBOOLZDTyfow0VqibRiAxFYNgEwJkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-02T20:52:16Z"
    mac: ENC[AES256_GCM,data:LxUSfo4MJg/eK16Z4aNeEKrcOT6/BvFN0Zpkmk/XwhsVon2bSPIFosso8gl3uoJHjj4b3Z/MqUCW0d5Q2Kr+wWrPzXV5B5TvaKFtQcB0tdhdE/n7Ain1Ivd68rz7OevGAEeHO4c9rqkpkYB3YJbRC9UNDru+1z6KQVvNBAG5TEk=,iv:V3aWRLU6e6DPMnrMrADnA8T3G3+cTDPLZ/0cFxd2uxg=,tag:m4xOnMIMnEAm5VaTkTi6ng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
