apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-password: ENC[AES256_GCM,data:xQsVVn5XObJhJ34Hw8LE5DCtWAw=,iv:f6lsv+JQz7+Fbo6IG+MQ0TcRSONcuHyclJzObgLgaIA=,tag:7ElRsRTgaOUG4KdcwHZrvg==,type:str]
    admin-user: ENC[AES256_GCM,data:rnwBlek=,iv:HZXW5aNnrQzkci0GBY5lWwCA+yygJi72a3/8ZuVcXT4=,tag:eT1FuyaIryX5a8v/I0Sp8Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxf6lyfrga0ddxltfhtgzvjkvq74yqjypcwxujpvh4grxp30u33su8s52d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0dzk5UGFNQnlvcWkxUTJG
            c1ZSVnZZeFB1dFJ6TjFtdERpU1BXbW5wV1hZClhDcVdONzFtZUFWVlRzWGVxQk1P
            a0hWTTI1YTBqUFVqSTVIWkFaai81RVUKLS0tIHcvZ0M3NEcvSUpYeHZySWZkb3Y5
            QkhRb1hOS3JFOTg2L29pZGY1NnZZREUKxZInR6XpoU1l7TP3eyuk39mmz3Mns9zR
            HVZ4CIPOoPlN42ZirhoiTN/jm6X+ddwDT0+Puq3Pq0sco2Km7MyLnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-30T20:53:48Z"
    mac: ENC[AES256_GCM,data:APgEIiUGjQBebVzAqd5VUSKd4xtUxXvseHIldXFQEIGst8H/CSaoj4Y62Yf8pqUAnmIqVCx0gwr51a1cGUye6xNWiDLpXGXCfO6AKUw7sGhsD+VsLhCk5Pl2WfDg7GlvMCdxfrdvhofnCiTKr0TOIxNHaxX2bnBGti/l5onhHbI=,iv:cpYIlwbOgeL1bPwSsZS/QsPNmZkEX01C1J1GpdYFx4w=,tag:gXwRRIjBNfTOlQxg/eFixg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
