apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-password: ENC[AES256_GCM,data:JWGMIZQ8EH4a7nSYQefh2QmG2/4=,iv:yjEgAAe1XxDyKR5W+9gx3Yg4uLeK9wenTSLUuvT1MV4=,tag:unxbJri+i1fJP9qbcNP6ug==,type:str]
    admin-user: ENC[AES256_GCM,data:83VHH80=,iv:qomhF/7QI2TZoNsL1grqkPh7q7xNBOveoUrbdm8vkNs=,tag:qS2icb5IOwtDi4oEGXMrTw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxf6lyfrga0ddxltfhtgzvjkvq74yqjypcwxujpvh4grxp30u33su8s52d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGbUpyRHpmYUp6LzJ6NTQ2
            MzBUdmovT1A4b0JEc2dnaGM5cXkweE5OSFRBCkFnYTVuUWR5dWppR0hZTGJRYUVp
            RUxBK2lubFh2cjVaZ2pIdWRuTmtDcjgKLS0tIHdBTGIvdXc1LzlSNnZjanNOa2p3
            Y05tOEV1Q3hXQSs5c21BUmtaNjBUM2sKwQxfPdjYHLqe4dOvuxsA8VuSdjMZlm/z
            Bkdm0nP2FFJmZ1upQQtbCrMBklw9e3LeX6eTtHv5lJ5X6Z6wfGNkZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-29T21:58:02Z"
    mac: ENC[AES256_GCM,data:JirvM/q4OQzZ9fa0zTbxh1XFa+saxwpL5mR0NZlANGy+W/fQ/Q1SO9gs77xWVdvpHQR0pA8c2kPJSc5BEt95sqTyUIFJ0eR8Ho2ipkhBpYvp7GK5aB2vVuU70xkdufURqsgEJqcpyFsZo1nHB6GcI/6K6tIIkNkD6emn1XgiW9Q=,iv:fT5lI8A4mEtMmsY81pukU9ho3yMoJWRzUErDkVkElCw=,tag:64BTZPKex2KSjpn9d3nAjg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
