apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-password: ENC[AES256_GCM,data:LLoXo3O7M76VYXdLaK61KMU8CCE=,iv:xbremXcghtnPq4VmNt1OCGzLRW2zb37BRYy+9es3MlA=,tag:mjGzcyG4uisrBM7N7zu6NA==,type:str]
    admin-user: ENC[AES256_GCM,data:H50u8HE=,iv:ISH1pfzSlo+1WzBE50UDXtFapPKwnbM16T0WvHN1MDE=,tag:0Yb7buWBS0ArjhqSa2S5aw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxf6lyfrga0ddxltfhtgzvjkvq74yqjypcwxujpvh4grxp30u33su8s52d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRWXM3NkhnbU9QZ0U5WmZT
            SUNvS1hnc05rNDVXcTBub2dtMEU3TS9udm1FCmhGcUVqbVdoSkt5WlJxc1VYejRa
            VE5MdDN0WWpsOWtZWFVrZmRUQWYxaEEKLS0tIHpFRWw0L2JqWi8xUEhLejVTZnUx
            RDdkVi81MU90NkJFVjA5cE8rc0xFajgKsd6byPSoYlqy1GM67ytboB6L8obTfV3V
            U6TTzZBODU9HXTHzXnO865xOH5K2c9XoOheLW633ZM9hrewUC543zA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-02T01:22:20Z"
    mac: ENC[AES256_GCM,data:Xzjaf6dpgsJRMBfSVaNbEoSGJfeTgUTs55LWEbmgmNbAX9VwGMTxSoWaxMnSF5kRGkMmihZRMoqajSUrGSYq4GQ6Z13kGIOpYpGhqsVmwYsKlXmltF0Op540ISAbwr1D0fSbmatpDOAcsz1ZLerEuuhZLJE9G9qUZd2uoWUGHw8=,iv:JHSnkt8BNGC6BIy1mYbQeQYkfdmF5/FDNcBYxBDQnTQ=,tag:30w0jBLyBb3RMHJAVLw0ig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
