---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

tasks:
  diff:
    desc: Run flux diff in a container
    cmds:
      - docker run --rm -v ${PWD}:/workspace -w /workspace ghcr.io/allenporter/flux-local:v7.10.0 diff --kubeconfig=/workspace/.kube/config --git-branch=main --git-path=kubernetes/apps --git-url=ssh://

  test:
    desc: Run flux test in a container
    cmds:
      - docker run --rm -v ${PWD}:/workspace -w /workspace ghcr.io/allenporter/flux-local:v7.10.0 test --all-namespaces --enable-helm --path /workspace/kubernetes/flux/cluster --verbose
