---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pihole-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: pihole-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: pihole
        property: pihole-password
    - extract:
        key: pihole
        property: pihole-server
