---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app pihole
  namespace: &namespace networking
spec:
  interval: 30m
  chart:
    spec:
      chart: pihole
      version: 2.29.0
      sourceRef:
        kind: HelmRepository
        name: pihole
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    extraEnvVars:
      FTLCONF_misc_dnsmasq_lines: no-0x20-encode
    monitoring:
      podMonitor:
        enabled: true
      sidecar:
        enabled: true
        image:
          pullPolicy: "IfNotPresent"
          repository: "ekofr/pihole-exporter"
          tag: "v1.0.1"
        port: 9617
        resources:
          limits:
            memory: "128Mi"
    admin:
      existingSecret: pihole-secret
      passwordKey: pihole-password
    doh:
      enabled: true
      name: "cloudflared"
      repository: "ghcr.io/crazy-max/cloudflared"
      tag: "2023.8.0"
    serviceDhcp:
      enabled: false
    serviceDns:
      mixedService: true
      type: LoadBalancer
      externalTrafficPolicy: Local
      loadBalancerIP: 10.20.0.158
      annotations:
        io.cilium/lb-ipam-ips: 10.20.0.158
    virtualHost: "pihole-k8s.${SECRET_DOMAIN}"
    ingress:
      enabled: true
      ingressClassName: internal
      annotations:
        external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
      path: /
      hosts:
        - &host "pihole-k8s.${SECRET_DOMAIN}"
      tls:
        - hosts:
            - *host
    persistentVolumeClaim:
      enabled: false
    replicaCount: 1