apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: &app pihole
    app.kubernetes.io/name: *app
    app: *app
  name: *app
  namespace: networking
spec:
  endpoints:
    - interval: 1m
      path: /metrics
      port: 9617
      scheme: http
      scrapeTimeout: 10s
  jobLabel: *app
  namespaceSelector:
    matchNames:
      - networking
  selector:
    matchLabels:
      app: *app

