apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:tKL3m0d+TV+NdiAS7JsIl19QBppH2RDB,iv:9FmjP0skROVjvEZQFYMRTazLRoo0Q9DDTaYBP27w7nw=,tag:zD1/H0IhVairmqYBMbJAtw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxf6lyfrga0ddxltfhtgzvjkvq74yqjypcwxujpvh4grxp30u33su8s52d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIaytRRUw4RXBCMmhHUHM5
            UkcvUDBOMEY1RUppQ05MTmFTZFVrQWx5Y2tRClhmRUFiaHpleWJlaUtzUVBTZFcr
            bjZBd2lKWElTRGttQ1E1bzZQcHJNa1EKLS0tIGFMenZ2ZHhPZ1A1WDBqL2tYVm56
            QzVGWHFlSWlXSFlrZ3FqZGgvUU14dWMKYFXyMfD6nmRPpJyeuwW/RmemekCK0QXR
            6YeWV3tLm0tPpJiJE6NRElV0sgMMPKOruNrcyS2FK/NbhzX4gyc1eg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-30T21:21:07Z"
    mac: ENC[AES256_GCM,data:KXxRTEGGqhpZby20mz0R+Gh4mwGTnZP7afUGO8+xSlIQG7o8G28ZH5n1hgqIzh3DC7BcJokXy9koC0yLMnf/R+KcmuYzPZCnhgKffOB8ZY+dGyz7iGADoi7G4vhvLPGL33BS3lc2vOG3ATenYfu3nEj6uQ8TfglKfffXUEhoH4g=,iv:74phCtCh0306mrqTbmUO2OfexAy3RjUtpQWzv9ktUoA=,tag:cjIOvvAYXDMdSNOdTKOVSA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
