apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:NHKsxfFjl85LRQ17X6HPkBwjLi4DqVc0,iv:OslCqz3KkKvXTff5N/KOJsC42+TaOdrbJXPYvVehj+E=,tag:dKd5ixxlfR8n4Bel+VontA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxf6lyfrga0ddxltfhtgzvjkvq74yqjypcwxujpvh4grxp30u33su8s52d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFVEJLNlhNQnExNzNHZnc0
            VXVmVXZMWVRUTDYySUlMZWFpOFNKaVQrNGg4CkIwYkxHK04ySVp4NENrK3ppQXh2
            bWxLVW5yajNqZS84VlVhQlowT2JVQ2MKLS0tIHN6KzlFOElEZFJHalB0YlJvUHBZ
            cEJRUTJ0Mi9aaGh5SFFYQTVYaW16NDgKMEj1us1Y/LJcZsnIq/kxlZ99u5UB7lHG
            O/rxi3cOrdwxc+jFJHk7O+5uBsW6jWzvDbkY0OzQKbRXvv5ayS4Srw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-30T17:14:55Z"
    mac: ENC[AES256_GCM,data:GGT9OycudKMPk31DOHmAin63c6Jd7Pbeh+H6SlwYFVUKmTAMXu48JMiyZuhSBMnkxZdpcKagBthIjP1ehpAsXLcKYkYDeS5fBHmUr4sAwsPdV19jzJ5MtIvbPDuWDFjl3HXLV0PJuVHpU9if08DA6Qcdv6Ocemlj46KS/Eme1oQ=,iv:1oQhfQ+c9qL9rFtaoKiHH3wI2dBtKfP0wQIaiqsJZq0=,tag:Q5Ibs2eqlvmPvYVyxg/6mQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
