apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:4i25PsotSKYowBUQbXjFKjakgOAN5bzT,iv:aLj9ZvJw6jgwDzu4dlVl9Z7IFtNLIDuDX+/PqXlut54=,tag:erntt8L8iML1fVzU4LbyXw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxf6lyfrga0ddxltfhtgzvjkvq74yqjypcwxujpvh4grxp30u33su8s52d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArK3AwSmQ4ck9sZnl6RHgw
            aUk0MUpxbS9OMGJjSUVxSWFQU1JkVmJMeHdrCk1GUXFGNDR3YzFmc1d2Yi94RW4v
            bnNOMlFNS3lMaVJQZ0JSUlF6YnhTRHcKLS0tIDM3UkRYK3hLSWRxdU44VmsxOFhy
            Qi9nOWFvckRuZk1INnp2VGcvSktKOVkK7WhDBno+gchAnxhXA4SGRB/zDG6atyXG
            KGdvaJDK4skj/VNQeTqw4p4wbkQi5FhQYt6RzZTXv/TbAKleyRAe/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-29T21:25:02Z"
    mac: ENC[AES256_GCM,data:2nLlf98TFSoQCDxTL9HWuAY8OHrffOCB/qRMNwzFUtTn742CHqkpptb5G0NNPSYGRWn8izIjcHsu+SSsoluc4kEc/NmyJ+cqdl8C+s/nChldqeXVxGNQdXKztRgzFZF1n/cCp6/NHRN41ifOcFULJrizOA5BSLtu8EGZaHkhgMg=,iv:RQ14nN7bA3uHVv4h4/zgv4bmc2FH3W7HZ85XCJ2nGeg=,tag:p3pjcMpjqbdDkyqt9Og7hg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
