apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:iTRJgdqksQArW6zO9pxT2UH0gUmvvqWm,iv:ycMaYhOZxxHcS4p8YBAGgo5f3SNXQdE2G4K7pHsl+K0=,tag:sKiVDuyr8rCr51Y4/P52Ag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxf6lyfrga0ddxltfhtgzvjkvq74yqjypcwxujpvh4grxp30u33su8s52d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFSzJHQjFWZGJFYTJaRUpH
            L1lybGIzbnlWWG53blAzcy9zT2J2VDFCRkdjClNKVnBKVVV4dFQyelZ2RHhFTU9L
            QXpNRE50UmFvREErZTVGcEFXQnd6c1UKLS0tIFdJVEl2L2c3bk9jVmgwOUtNZTVV
            ZFJpVENxbnl4ckpZYjhsWFF4ZXZmYWMKMdz6RDNdNTbVsTrPBbL2kw6o6uq8J8Vj
            rnd1SB/i/HBHj/B6Q25lcLUfsIOofBTGOWZagqiVvQ1tgerlcQ6FeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-29T21:48:09Z"
    mac: ENC[AES256_GCM,data:n4qfJB8DS/hQmqQkKZ2WTZ0NweBcZtJ4My5tiV/AjXXLoI5hiQtIeIXH+O8iff+xzFqK8XmtIqUqHqmeJJfRqUWcPbQzV9xglbcY3ub+rTqDrL6Wy5DLHvTeHRgvWltuhiVW6NlOY3QSAX8DcWQ2AH2ZPnmEZ5U30vpijyREBok=,iv:DoQbPzDFtkd0a3sNTr2CI7qfRDsW9+86cbAu9BPdI10=,tag:REO0IKG0tCt2wwx/qPL9QQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
