apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:lZM2qlQ1JInoQjaoaSp7l1t9AAmZ0rsr,iv:ebEdYm1Dbt7PiZf6K9XJ+cZbHVHhaKgdyYzNWb4nd1Y=,tag:khq4FyLIxgkX0yb3N6Qy6g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxf6lyfrga0ddxltfhtgzvjkvq74yqjypcwxujpvh4grxp30u33su8s52d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUOC9pbC9lNFAvVTIrSzh3
            YUhPcExVcG9pZElqTFNUY3k5bGlyTFdQeVV3CkJsTlltbTRmWUJRa0ZucFdaNXVo
            L0Z4UlJHelZvRlF1TGVDa0tONWVPK0UKLS0tIFYxVTJxazhjczhMMlJHeHExZExC
            NmpLbm5YWGVoVnpJdTAxT1lTWWdJUTgKLYG5n4LcSjq/jQdAQpKp6MFuqh9ev7xz
            X0klN3+TMAOyHANBXYZKfQ3OULzWA/l2LTcStCxh0sTp2e9N/8ldWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-02T01:22:14Z"
    mac: ENC[AES256_GCM,data:jWAlmkn4zDFC4ZuxZKKqL6OJSJOw9UitS6YCNnikHPYAnk12exYiebxfOEgt+vc3QzG5BzkltTRrWZ9e715lHinzWCSGeB4X1Wj4RYI6ilLvS/VUPcf0i5F2n3Ue7f26zz14Mz9ODoRtxcZo+NsYETKn3Tg8lDifG9oxLdAiPrU=,iv:RCBI/T83EsKm8vLRMj5R2m3ynga5kI4rwIkK1yfLd/I=,tag:/d7gR179vQkuM1o8GeUDgQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
