---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-dns-pihole
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.15.2
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: *app
    sources: ["service", "ingress"]
    registry: noop
    policy: upsert-only
    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/tarantini-io/external-dns-pihole-webhook
          tag: v1.0.0
        env:
          - name: PIHOLE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: external-dns-pihole-secret
                key: external-dns-pihole-secret
          - name: PIHOLE_SERVER
            valueFrom:
              secretKeyRef:
                name: external-dns-pihole-secret
                key: pihole-server
          - name: LOG_LEVEL
            value: *logLevel
        livenessProbe:
          httpGet:
            path: /healthz
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readyz
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5
    extraArgs:
      - --ingress-class=internal
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: external-dns-pihole-secret
