---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-dns-pihole
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.16.1
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: *app
    sources: ["service", "ingress"]
    registry: noop
    policy: upsert-only
    provider: pihole
    env:
      - name: EXTERNAL_DNS_PIHOLE_API_VERSION
        value: 6
      - name: EXTERNAL_DNS_PIHOLE_SERVER
        valueFrom:
          secretKeyRef:
            name: external-dns-pihole-secret
            key: pihole-server
      - name: EXTERNAL_DNS_PIHOLE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: external-dns-pihole-secret
            key: pihole-password
    extraArgs:
      - --ingress-class=internal
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: external-dns-pihole-secret
