apiVersion: v1
kind: Secret
metadata:
    name: external-dns-pihole-secret
stringData:
    pihole-password: ENC[AES256_GCM,data:z+ZKasIKdrU=,iv:UY2aqmoWiGu2MVeGEioMJSn7CF0NwmDPo7csA0JXAsU=,tag:TvlTnj8sgGjtWf1fup/3Vg==,type:str]
    pihole-server: ENC[AES256_GCM,data:bKcFrORQv45L5d+Q5VWgclU=,iv:9esppRYXmi7Vt+OuxQH7Q6aT4v7QlMcQqAbZzE/gLx0=,tag:lteZ050epfOjFZnaYd/bVw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxf6lyfrga0ddxltfhtgzvjkvq74yqjypcwxujpvh4grxp30u33su8s52d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXMkZuZzRQS0tKUytzQjlm
            SDNIL3hhTnduVHpXcWZBb2tMNUNaeHljN0JFCkxkczA3OUpaWkVlZnpTLzZIaUxG
            dDZ5SVRnbEVzbTE0THZvY3FWeGhMalUKLS0tIElGdThyRkFVZ0FzQkQ0ZDVGRy82
            U2Y3VmFVc2xJeHJtTjFqdEVYU0ZveWMK+YolVATBCggzl/SNrgF3NtOdXTSpyBfg
            I8WFYMYC8GEaLXakH9RwcZLcjFsIUiKw86zp3FpVVWWMwTFmFofYnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-07T16:56:02Z"
    mac: ENC[AES256_GCM,data:sdRJ+K+IUQxTOYmwcNLndu2r7j/mShJMUIkqtAtLONKYPFjW7wRYAe1Nl0SFYomd3xr5gBLKDdEJOYPu6mwyQkbBhM8zBDKjla2OGiMn1okcp03NC/YoO8AD6SA3V5wVITK1uidSSP7mOHhbCrXx9AcGHKNJqzDO0JBL2parYjo=,iv:PzTPkkIpzcHXP+V4Lts1+QQJcoi4XabDesOJcb7VPEE=,tag:JC+N7GCy7rXY2I3NEDNEBg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
