---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: coder
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: coder-secret
    template:
      engineVersion: v2
      data:
        INIT_POSTGRES_DBNAME: &dbName coder
        INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .CODER_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .CODER_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        CODER_PG_CONNECTION_URL: |
          postgres://{{ .CODER_POSTGRES_USER }}:{{ .CODER_POSTGRES_PASS }}@postgres16-rw.database.svc.cluster.local/coder
        CODER_OIDC_ISSUER_URL: "https://auth.${SECRET_DOMAIN}"
        CODER_OIDC_EMAIL_DOMAIN: "${SECRET_DOMAIN}"
        CODER_OIDC_CLIENT_SECRET: "{{ .CODER_OAUTH_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: coder
    - extract:
        key: cloudnative-pg