---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coder
spec:
  interval: 30m
  chart:
    spec:
      chart: coder
      version: 2.22.1
      sourceRef:
        kind: HelmRepository
        name: coder
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    coder:
      initContainers:
        - name: init-db
          image: ghcr.io/onedr0p/postgres-init:16
          envFrom: &envFrom
            - secretRef:
                name: coder-secret

      env:
        - name: CODER_ACCESS_URL
          value: "https://coder.${SECRET_DOMAIN}"
        - name: CODER_OIDC_CLIENT_ID
          value: "coder"

      envFrom:
        - secretRef:
            name: coder-secret

      ingress:
        enable: true
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
        host: &host "coder.${SECRET_DOMAIN}"
        className: internal
        tls:
          enable: true
