apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloudflare-secret
stringData:
    api-token: ENC[AES256_GCM,data:YPIq1V9vkeDMoYfQZc9GMaAg/PzpyStv1EzYI7XkopWXDGX4sK0lCw==,iv:XJU+TpjVq7wBMw4oWHKJcwQa8wKfiOHH4fUT9YbN70Y=,tag:4VnsjrwJpReT9p6d2Pu9wA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxf6lyfrga0ddxltfhtgzvjkvq74yqjypcwxujpvh4grxp30u33su8s52d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBidkI0RnhxcERYNjhTdmhX
            dHp4NnExR3lQZ1FLeU0rWE14a3libEhRdkdjClBQaTZFOW9aaGJIdituYmJlT2tq
            blF4UFhYRzBXenozQ0hsMkN3dW9WNEkKLS0tIFcxZ01mMXNQdzZrUWI3THpFVks5
            T3RKOGkzMEVvUTBZaFNpZlIzTnZ3RW8Kw60ezfmR8M/ANiQAaNtGYj61SaYxqRYl
            a2PWNrXRlU5rNaYgRhmh2+4LGdGqVsb69sXAGrpRCgfbp76ZdmzHig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-30T21:10:16Z"
    mac: ENC[AES256_GCM,data:DSbFAPrxV6J3HPKPB+ipKlz3JZvOyM4UoDDfprJRuYdlQmShuW1s3K5ERg5dID4UMhi5EApVko0hGV9NOfEwMVJ7nchCN6Js5oSALIg674gnPEgEdVo6CLN1+aJZFk7WkPReiWcoEGYAmcokHLYbpQYal2zBzrn5ZWMUqlVSBaE=,iv:+uCyGqFhE6GEbrS9qHPRu5WQuFeiBo6Lcco/KUtMDgc=,tag:O1t2Zao2oy4cyQvTuSAXXw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
