apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloudflare-secret
stringData:
    api-token: ENC[AES256_GCM,data:nylve4VfKXEoephhi3duUQ9ObylxljAfMMg0ZGjr+uxcLJrXFjsvZg==,iv:7D9mdlFcUHpxZBjkoDCwfGPCQZO0T5IbdK/D/dSgcv0=,tag:1TTY55xPl2d0gBufrR77fQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxf6lyfrga0ddxltfhtgzvjkvq74yqjypcwxujpvh4grxp30u33su8s52d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvU1lTWFhEcXNDMlZoS2g3
            K1RoN1BGU2NqejdLWmg1WVgxYUxMelZJaEJZCkY1NTBPMFd4YzE3ZnY3WWxjWUxW
            RS82b1FKZUhTeHVQSlQ4QmUybC9heUUKLS0tIE1BRldQTmdDcGQzWVFwSkI2eEpW
            K1JvNnNtcjVObXV5d1FCazRyS3FkKzAKpS+WxjzpPVGiTKEXC/auTz50Ha0QpvaL
            /sDyGtAnNxDdU1nfGcZPoSYPBJ+cOFZCKjrntdlvpHfjF+LYaQjIrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-30T20:53:43Z"
    mac: ENC[AES256_GCM,data:KiMJfPcv5SYzglcOpghP6ov4H1uXHqm2aLP/bxu3gLnwmgf0BGR6z8et0UqBV0dHoPjt0s/ST2GKeneaSC7W6A8xT/SEmkoiTgt0QfXoQTHCtGaZePpd3VtJigvvwPmxJPvd3pemgXj68jQBAZCGrKXrx2w9Qp6n+FBDg3/B5PQ=,iv:gSR2ls4qGtpsjJDASNlQtnWYBRuEa3YC1MzDzFBlzjI=,tag:QeVEq0HyqM21njgbJKwZ/Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
