apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloudflare-secret
stringData:
    api-token: ENC[AES256_GCM,data:QT+JL55yEe/l9CBCeJqRq/SO5GjQ6+2LIpurZUg+dltB2evSvbBplA==,iv:US93wQECBkwQXhVdD6u2TiVHvEjedN7rEEL8QtKcSBo=,tag:5EvcJikWHNgojWiqNxslaA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxf6lyfrga0ddxltfhtgzvjkvq74yqjypcwxujpvh4grxp30u33su8s52d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3RTd2czBLRjdLeTJuLytY
            bkgwVFp3N2lVREJ3VHVoTVR3NXdiVjdHU1VjCmhlZTAwMGp6eHFnaWV3OXRxUjJq
            TGJyMEVQQ0lxVjdwSk9BdU1CUE5TalkKLS0tIG9VZHhZQ0lmRTF6NkQ1V1BYMXdm
            dmlST3pPSisweGJVc1pMMmJRY0thRVkKbn5dYiitNYYsFiLOvVuKlErg9CB6Pcdf
            811KVngrlWs4KjHOgwVoTiOqqe+QcxB7qT/Hv3oRr1H7HiuBhmnIRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-02T14:10:01Z"
    mac: ENC[AES256_GCM,data:UEn7y8rmBmlwcaZQfOIf4TaYtAXgBJtpiGjldWQuULUTB/cQKUKdJNsP4RZbOx5HOyEVO8rG18ZEflKX0p5vsR31vSpOmMQQJ2R0qKd0dyXIFv+0/4nYJtUQrMm3VLYhOXFTFbM866gI+0UMWxfVg8Empimtf29UOkaBCzBhaZs=,iv:boVSSasd8cQjfQtalaptCfvp18V0IepNftHWSPQhXbE=,tag:HUQ3vEfT1p9Mm/ysEYA9HA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
