apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloudflare-secret
stringData:
    api-token: ENC[AES256_GCM,data:aGFxpFnm9m6owxXHYXKjN4VEThiUIUpR1kClDVEALl90K1jh4mJkZA==,iv:Qmwk5bxAQH8sbfPCuI9j8X0knGXZ6aKpJfWHkhuLna0=,tag:+k8xIRuskmlTUVgioEDg7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxf6lyfrga0ddxltfhtgzvjkvq74yqjypcwxujpvh4grxp30u33su8s52d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1c0VQOGJvTzZHdlUrMnd3
            eW1kam1rK1I3bS9uYkN6VFZSWGRsNGkzbW04ClB6SWZwOTM3TkluTVkrcUZMS1ZD
            em54VDdCNmZlVzQwa05ueHVCdnZ1cjgKLS0tIGJjcGtTbG9LYlRLSEtNZnJWaDJT
            ekhoc2tlamU1cHROWG9xMVRUd3JyeEUKsBc86aWB78+edsyg9QZzyCYqIwR9ehVO
            /t29W81YdWCUfjEN9H2dlqHVlIEWZwEBOTlstPiTbHncxJL8BjWyjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-02T02:53:04Z"
    mac: ENC[AES256_GCM,data:fXYuQNOpFlgpqI9UjaMySFEez1ZoyDwriBSO4ZhbTAD+EKWMJJXZ9RBZRCbhZrikwjGpc5wLksqeSvcq1tr6rmPbzKNqGiDNEt4h5KjIWW/1QPjtDyJDuyso+selGXqJpMQZ3esgf05aY9EHkuCZJIIOuipVAwLnyFrXcPRsSd8=,iv:SkX76X8yNCAzGj9iMVk6aM+DKbs6y822HDW74yXo4ck=,tag:tCF9RwtxxDQ4WD/cSDcJbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
