---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gatus-dns-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: gatus-dns-config-secret
    creationPolicy: Owner
    template:
      metadata:
        labels:
          gatus.io/enabled: "true"
      templateFrom:
        - configMap:
            name: gatus-external-service-tpl
            items:
              - key: config.yaml
  dataFrom:
    - extract:
        key: pihole
