---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "${APP}-gatus-ep"
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: "${APP}"
        group: hardware
        url: "tcp://${IP}}}:${PORT}"
        interval: 30s
        conditions:
          - "[CONNECTED] == true"