---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: code-server
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: code-server-secret
    template:
      engineVersion: v2
      data:
        PASSWORD: "{{ .CODE_SERVER_PASSWORD }}"
  dataFrom:
    - extract:
        key: code-server