apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:fOjLYseYsg6uTHhC5AYLIjyyIJjLUL9+ud95EIeISVz4NKdkM3Rxvg==,iv:AbRNoS4/02lxI6BOB0QxuNSkifxQMF2OmTzYPqeHGfg=,tag:126xpMyjNYjeRNBmizLtMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxf6lyfrga0ddxltfhtgzvjkvq74yqjypcwxujpvh4grxp30u33su8s52d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaYjBYaHo3WTRuOXNuRVNP
            QjVhb0NjVGg0MUtSdTU4VWhsM3kyRmZLa1NNCmZpYlJDUGFyKzJndU16dTZtVHZZ
            WFpWVlIrQVMxUTFKNExTdC9GV1pnakEKLS0tIDZ1d0FnZTB5Z09GYlVBVngwV20w
            RWlObnRKd1ZLUWhiaHNxcElCc0lGZncKeMkTcRUJiqrIa71iUrY/nilSUVT5c8yJ
            W1kSn7axSa6LbTvmXvG6xWTxQGY6oF98hfk+P3FtDq99mxxfGAnRqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-07T16:56:03Z"
    mac: ENC[AES256_GCM,data:Y+iPnuVG2r63PzcUNs1LruHsmUcYUQiKfcx7q9pj9d9bNjsrzOL5/3j0UZFqBRRhYLYuDsuvr29n1TpE2f1YQocp7CpclN4c+c7FQIeROJ/1pb3Deu+thz5Z1w/+gABm181tbbq6oJNjPKkOKcSFdAwQDIyjEJdx2YfOanDBlXU=,iv:C5qDGxXo4mN7Z9sGLZeHBZATw4t6x1oMVjN2GpHPLM8=,tag:C4BTvNF9m6p9NfbT23vaDg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
