apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:060MtUzSrb6rUPnMOVPgcricR+FPn1XXw8GmKhq5My/9Bw1njp1Oyg==,iv:4LuZ8LzR81x04hakItagfqyfVtBjkuWqm9pzPH1tQM0=,tag:carEEyqjLowT3hYsfG4a7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxf6lyfrga0ddxltfhtgzvjkvq74yqjypcwxujpvh4grxp30u33su8s52d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWWGF5YjA1QnAyanl4Z1NK
            TVQvQmdPdnloTno4S3lWck9wQUd6RmwxSm1ZCkNXajJXb2tFSEF1UDh1WnlhMVJC
            UFFQalkzUkRwK1NGb3pGQXF4ZFdrcHMKLS0tIERXd0M0M3ZoZUpqNVpueFpWR3FG
            QUhScWZGSlFrZFFMQUJqdk5oQ2JJdGsKVgzK5mSBhVmDJ7mXkWXjSITA1VOobyxe
            iNq1fFjum4mi3f7iQws2wC7JncLHobGzWjmZ8We+f1Po1Pf7FP7nJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-30T20:53:45Z"
    mac: ENC[AES256_GCM,data:1MOYx85G5W4NpyhH+8Is6uXPk3Ma7DsWCUKsZKtml9PI3TYRc9hA4hRNa2TR5W+czwoJOR+RzH4vxBoQodjJD8/bWni6GiW/INnQ0rGzkWBbnTmLhRvuf0od1Hx6MNXEj6jVgsPACcphNhB9ex+gKcPofdhtBgTDa/wUyZYZ0Dw=,iv:IixOIvG//pAq+8Cynj4qP2RrIyaVqfK9z2Z18Y1B300=,tag:g2UltffVUrirlcAdov5xFw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
