apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:rhP7BsAEyTZnh/uxMMYt1USFOKYeyZBy0Xel4NCABSo4WuEiIqjwvA==,iv:tu3+78HEZB5f9MbZl0GE0bjB2V7l//MfBGASY6iD1UI=,tag:5SHiHnqlkuVTJ3skJA47hw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxf6lyfrga0ddxltfhtgzvjkvq74yqjypcwxujpvh4grxp30u33su8s52d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1RGhyajdIL015OFdyMUU3
            S25iZGhzNTJrSWE2Q29hSUE4UHp0ZmdnTVhjCkJPWnVDZVIwMTZEejhKc05HbkU3
            U2tmV2FFZzNGS08vTUpoM0JQTEZIYzAKLS0tIGtsN0NBbktWYjdFazNjUXpUdU55
            cU8yOFk2L3FlUUQyRkd2Q0JPbldpTm8Kp8nV25Kk/cKI7s6Wd7gshB/ebwBl3WbR
            d1d7rKsUQxdFIh5iobRJbX3EN1FNm8oU8ELmr5fq+PZvCQGvxSZBVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-29T21:57:59Z"
    mac: ENC[AES256_GCM,data:Wx4tZl0cS7hl0tf6kBYXj3jhn7znUk4NoXI5fok97vDd4gMknsl197zyuelR7fb87mU52MfJPocHbPcZKmpI+0Mm/0g1WIF1iTobZhojpnwxGPpScD4eOdWObpqh0iZG5/l1WN4YwunvBti8goyFk2Q+7/irgBLCZBqyzhSkNIc=,iv:ORzF9gbgj4iFhD0wwiSfElCWDr7KAjV3txEnty0TeTk=,tag:4BLaTkI+MzIcKuqEIHIyTA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
