apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:aURCudS2pFXhp4iOAiI1b9oRC1GG7Q4MMmkHoCAq1ImULqdNbgKiCQ==,iv:gICfWS5zIpXxhray4jli2mSC77Nbe1opMB6dEpjdpaI=,tag:Ya799qCpz8Ls56fsHzsH7g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxf6lyfrga0ddxltfhtgzvjkvq74yqjypcwxujpvh4grxp30u33su8s52d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0MHZHaHNOWXRFeHROQVA0
            UFYzbDBZckpTUHpET3FTWGduQjlVUUwyeVdFCmtyMVRrampmb0tmRGlxYzhyQmVG
            aVB1L2x3S2k0eFZaSmNNYUZaYWNVMkkKLS0tIFFFRHZvQUpFa0RZTk5SNmM0NHRY
            bm5zSDllMXNVeWZheHZOb2lwUkEzRWcKRiUWOVqBMA1gfwUuUx321Hob9hu7V26r
            5rw5FEWxawB8xB3wFocLgwllmY/Cu3DLjuJsL0AO5VwMF+K1CgfTYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-07T18:07:44Z"
    mac: ENC[AES256_GCM,data:rn4qofp8S70K4Gf6HgXHpddkMbgAEKP5Xlx6rI/RRh44Ta4HJwq1Y65Lil4TXHTzLRBu4iGyMW3xb0uvYMe0EVlnpRRkyDYwiDm+fc58EhE2bvAXFi8Vv51AEjV7z18gjQdtSTPUUEB+L4laFZVaO8kRh4OQqpOBlxk+7QomycA=,iv:H7As0hSv0CA26+PNLq9OY1BZd8NvmdJnWV+bNlUeOCU=,tag:x44X6nDtIW7StjxXBbOC7Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
