---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rocketchat
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: rocketchat-secret
    template:
      engineVersion: v2
      data:
        mongodb-passwords: "{{ .mongodb_passwords }}"
        mongodb-root-password: "{{ .mongodb_root_password }}"
  dataFrom:
    - extract:
        key: rocketchat
