---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rocketchat
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: rocketchat-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: rocketchat
        property: mongodb-passwords
    - extract:
        key: rocketchat
        property: mongodb-root-password
    - extract:
        key: rocketchat
        property: mongo-uri
    - extract:
        key: rocketchat
        property: mongo-oplog-uri
    - extract:
        key: rocketchat
        property: mongodb-replica-set-key
    - extract:
        key: rocketchat
        property: ADMIN_USERNAME
    - extract:
        key: rocketchat
        property: ADMIN_NAME
    - extract:
        key: rocketchat
        property: ADMIN_EMAIL
    - extract:
        key: rocketchat
        property: ADMIN_PASS
    - extract:
        key: rocketchat
        property: OVERWRITE_SETTING_Show_Setup_Wizard
    - extract:
        key: rocketchat
        property: INITIAL_USER
    - extract:
        key: rocketchat
        property: mail-url
