---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rocketchat
spec:
  interval: 30m
  chart:
    spec:
      chart: rocketchat
      version: 6.23.2
      sourceRef:
        kind: HelmRepository
        name: rocketchat
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image: 6.13.0

    host: &host chat.${SECRET_DOMAIN}

    smtp:
      host: smtp-relay.default.svc.cluster.local
      port: 25

    mongodb:
      enabled: true
      persistence:
        enabled: true
        storageClass: synology-csi-iscsi-retain
      auth:
        existingSecret: rocketchat-secret

    persistence:
      enabled:
        storageClass: synology-csi-iscsi-retain

    resources:
      requests:
        memory: 512Mi
        cpu: 300m
      limits:
        memory: 1Gi
        cpu: 500m

    ingress:
      enabled: true
      ingressClassName: internal
      annotations:
        external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
      tls:
        - hosts:
            - *host


