---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "smtp-gatus-ep"
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: "smtp"
        group: internal
        url: 1.1.1.1
        interval: 1m
        ui:
          hide-hostname: true
          hide-url: true
        dns:
          query-name: "smtp-relay.default.cluster.local"
          query-type: A
        conditions:
          - "len([BODY]) == 0"