---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "smtp-gatus-ep"
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: "smtp"
        group: internal
        url: "tcp://smtp-relay.default.cluster.local:25"
        interval: 30s
        conditions:
          - "[CONNECTED] == true"