---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app smtp-relay
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      smtp-relay:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            controller: smtp-relay
            image:
              repository: ghcr.io/foxcpp/maddy
              tag: 0.7.1
            env:
              SMTP_RELAY_SMTP_PORT: &port 25
              SMTP_RELAY_METRICS_PORT: &metricsPort 8080
              SMTP_RELAY_SERVER_PORT: 465
            envFrom:
              - secretRef:
                  name: smtp-relay-secret
            resources:
              requests:
                cpu: 5m
                memory: 128M
              limits:
                memory: 256M
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: *app
    service:
      app:
        controller: smtp-relay
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 10.20.0.155
        ports:
          http:
            port: *metricsPort
          smtp:
            port: *port
    serviceMonitor:
      app:
        serviceName: smtp-relay
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s
    persistence:
      config:
        enabled: true
        type: configMap
        name: smtp-relay-configmap
        globalMounts:
          - path: /data/maddy.conf
            subPath: maddy.conf
            readOnly: true
      cache:
        type: emptyDir
        globalMounts:
          - path: /cache