apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:GSADjsniY8U4YLYl52SPl4yGl2F9WOuwN7JK8vldrQ7EUFPLx9keZg==,iv:SZY2Y9W6gbvl7yaYtIhJqoplhbDHkOglKPI7VqyYL6g=,tag:kz+RIqEOHJhkwRFhG1Sv3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxf6lyfrga0ddxltfhtgzvjkvq74yqjypcwxujpvh4grxp30u33su8s52d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZWk9iWTVsT2RBMFJUYzJJ
            bVh0LzVGWFNON1AxcElySFFhY1NwS1VQWjFJCm9RUEI1NjgydmQyY2duVE4wK0VY
            NDJqTERsK3A1K0pzQWUwclhBdm1KNkkKLS0tIENBQ3k1QnlqdFFTQlJMWEV6RmZS
            RE1qQ3ZuS3hHSW9RUHhjbzRsc3NTdWcKPufyMAEUnVqinlTVUeVwYTB60oibgFVu
            pazk5VbO8efUyVUjXyczdOKDsCF28RYz3Oev4yNB4WTtoN6+KV3OJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-29T21:48:09Z"
    mac: ENC[AES256_GCM,data:kvpTh8yNNL43dgtiSRm/7sMwcYXSJsSLrPWOWHNsk9euWVIE8qLjMBGhfeZELVV6CUf5GWcAnlwLd+QfmYyFe5vkrc8o11HgJ75LrM2GtIhraBbwHLb+Ts+Yihs6UGmphwfj63Fbyt63alfgjeaZgGU3hAbrNPAzQJydnWe4xPo=,iv:ToK/sJLUTWYMJY60o1GGs3MhX4zqw3vQUglDlSBdhQg=,tag:Qv6OoiLhgdhHkDu9OAWgSg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
