apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:cc0BWw9E++wbbJxDLAknYtAz0rdpo/HngfD5YO9e9zWsOheHICnI4g==,iv:lqsiBXsKiiebx/P2RtLY2qcuZqdmjUxRSVXTHB+g3f8=,tag:8CvCGwps0uwGIg6bG2p2Gg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxf6lyfrga0ddxltfhtgzvjkvq74yqjypcwxujpvh4grxp30u33su8s52d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZUZaL2xYVFRzWFROQ3k0
            TDE3OTVMUVdWaElVZG5paXFoYzhGT1BHSm1nCmVFRjkrN2ZzTXFNdUxDWnVjeXM4
            S3VIcXVaazVXK2taRUFzenNOYXA0VUkKLS0tIGxUWmpyMEFOcHI4dXlCU1htdnhY
            U1JOVWQrTU9LS0tSS0R3dUJYbElvNjgKmgZG5SAzZU/0VaeKFOS1TvcdEPSdMjbj
            UUm38M3U1LHMIpUhXmv5W2kOaexwmu1QqLrTYb1kguYSxUWF7frBcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-29T02:30:53Z"
    mac: ENC[AES256_GCM,data:ueNBO99MvDFdZPZ94Ivp3KcexPyjeYrMChHczqmD7KTZWDpOr+LIDsrochRgbiQcwp+W9gpPNl3ATaeEufejN5f0GntoB8/j/FfJXYfsmXf5gBRm/Us90hLtaZCO34HBTXsl3ua0eeFcYLWEGiY3SONrNf/K6kRacinmF/CFSSk=,iv:tF+jiL8OtcbJqmUGU4sDgewfpeoooEr9cbKzXnBG/r4=,tag:F3nUUaiVpuON7/pFpTsZQg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
