apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:JmAguambSdFP4JC5P9z5VTv75EDMBail0He9Ur9mXnNVbbNSO8yCFQ==,iv:ZbfREo6KPxApILzW2jqjmGxRS3sejTU9WLPMp0TZV7o=,tag:tEJODbIFF/HHbu8mcG5Guw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxf6lyfrga0ddxltfhtgzvjkvq74yqjypcwxujpvh4grxp30u33su8s52d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRk9BY0NyY0U2LzQzb1Jj
            SllGZUhPVHBHYkdjakhTOTJLM1U2eXlYWW5JClI0TjB3cU9XdHphMWJwYWJzcEp1
            aFJHWXk3bVduakVLTGdxOTFoRGNpT0UKLS0tIHNuWUdWTGgwTWNwWjlFZGVYRkxr
            TVQzTEZYZExWR3cycmorSGRuQTdFbjQKXiqnZ2JVg4HXf/3v/WROCHW0niBkKwDx
            Hs725rhvRfL5qcbJOzsaSY2V3RyRA3oPaYx7cMuZFxSxpE3ndw61jA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-29T21:57:58Z"
    mac: ENC[AES256_GCM,data:8fWm/13tQ0Gyg9XgkOhjlzPYMt5y5Vw2RfsYooyg8UhBiqqBhro5N86BDIvDE+wjiaTQrJdBFeLlUt+u+olfEyX/4xEpRlLKuIoOg5LLbT+WU5aO9/rdVz+BdrL/aeHhYE5rxC6sbb4f7FY1ihVc8TbEVrPzp3K1+ufSwki8Kxg=,iv:ub0kCivoX0V/N10iRAl8Ds3a/QZoe8/17B7/Fk0jh14=,tag:tYtGajR/ybjsBKWyEAobwg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
