---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: glauth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: glauth-secret
    template:
      engineVersion: v2
      # Create passbcrypt:
      #   "https://gchq.github.io/CyberChef/#recipe=Bcrypt(12)To_Hex('None',0)"
      # or
      #   htpasswd -bnBC 10 "" YOUR_PASSWORD | tr -d ':\n' | od -A n -t x1 | sed 's/ *//g' | tr -d '\n'
      data:
        config.toml: |
          debug = true
          [api]
            enabled = true
            tls = false
            listen = "0.0.0.0:5555"
          [ldap]
            enabled = true
            listen = "0.0.0.0:389"
          [ldaps]
            enabled = false
          [backend]
            datastore = "config"
            baseDN = "{{ .GLAUTH_BASE_DN }}"

          [[groups]]
            name = "svcaccts"
            gidnumber = 7000
          [[groups]]
            name = "admins"
            gidnumber = 7001
          [[groups]]
            name = "people"
            gidnumber = 7002

          [[users]]
            name = "authelia"
            uidnumber = 5000
            primarygroup = 7000
            passbcrypt = "{{ .GLAUTH_AUTHELIA_PASSWORD_BCRYPT }}"
            [[users.capabilities]]
              action = "search"
              object = "*"
          [[users]]
            name = "chris"
            mail = "{{ .GLAUTH_CHRIS_EMAIL }}"
            givenname = "Chris"
            sn = "Smith"
            uidnumber = 5001
            primarygroup = 7002
            othergroups = [ 7001 ]
            passbcrypt = "{{ .GLAUTH_CHRIS_PASSWORD_BCRYPT }}"
          [[users]]
            name = "josh"
            mail = "{{ .GLAUTH_JOSH_EMAIL }}"
            givenname = "Josh"
            sn = "Smith"
            uidnumber = 5002
            primarygroup = 7002
            othergroups = [ 7001 ]
            passbcrypt = "{{ .GLAUTH_JOSH_PASSWORD_BCRYPT }}"
  dataFrom:
    - extract:
        key: glauth
