---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitops-admin-auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cluster-user-auth
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        password: "{{ .ADMIN_PASSWORD }}"
        username: "{{ .ADMIN_USERNAME }}"
  dataFrom:
    - extract:
        key: gitops
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitops-oidc-auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: oidc-auth # weave-gitops expects this name
    template:
      data:
        clientID: weave-gitops
        clientSecret: "{{ .GITOPS_OAUTH_CLIENT_SECRET_HASH }}"
        issuerURL: https://auth.${SECRET_DOMAIN}/.well-known/openid-configuration
        redirectURL: https://gitops.${SECRET_DOMAIN}/oauth2/callback
        customScopes: openid,profile,email
        claimGroups: groups
        claimUsername: preferred_username
  dataFrom:
    - extract:
        key: gitops