---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
spec:
  interval: 30m
  chart:
    spec:
      chart: weave-gitops
      version: 4.0.35
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    viewSecretsResourceNames: ["oidc-auth"]
    additionalArgs: ["--auth-methods",  "oidc"]
    adminUser:
      create: false
    envVars:
    - name: WEAVE_GITOPS_FEATURE_OIDC_BUTTON_LABEL
      value: "Login with Authelia"
    ingress:
      enabled: true
      className: internal
      annotations:
        hajimari.io/icon: sawtooth-wave
      hosts:
        - host: &host "gitops.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
    networkPolicy:
      create: false
    metrics:
      enabled: true
    rbac:
      create: true
      impersonationResourceNames: ["admins"]
    podAnnotations:
      secret.reloader.stakater.com/reload: oidc-auth
