apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
stringData:
    password: ENC[AES256_GCM,data:oRiQodRvlcVvjhxDxMRSO45mdqiOqsVACjqq6ydL5NJ0nRgbHkZOt8kEZdS0TjVqGtFHMVzTzbWHAyyx,iv:u15s+6r2mmgywhoDHInjQyGm91XVpqzX7nIRefmRWZs=,tag:Lt1AYTeZxf6cCTfhtTDCfA==,type:str]
    username: ENC[AES256_GCM,data:qzaUiKY=,iv:SQ4+8Wxd3pjTd4VPxfy89anKScNpfT0JNQrzrq/p+UI=,tag:0eI2riITT8auBmRXX01KVA==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxf6lyfrga0ddxltfhtgzvjkvq74yqjypcwxujpvh4grxp30u33su8s52d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2TEVscTBiQ2VJaW9RNGtC
            bmVFVmUzd1haVTlKa0gzaDBXNjR0WDlJN2xRClpQN3g5ZkhUQXA1eDY4REFQVi9t
            OHRxVUdTWld5KytBdVhxY0hjL2pKYXcKLS0tIENwU3pvTFBCZjNPemIwR09xNHh0
            RVU3RTlqVHAxVjJaZnZhdG1vL1NlVkUKn7P3xgFf5W2tYghkdCa9VimtSzuP3r9t
            TipmGglCtVFDeGRBSKVgWzTU+7gNV91ZkJSn0OmxnBIGqPCFZXOItA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-30T17:15:11Z"
    mac: ENC[AES256_GCM,data:9qadngvjNhrar9y9pGe4wIg/fvOeuqgVgeEuD8E+N8Pz8vkgyXHIKwvOCJM5wpqcFundzwVHTy10BJ6NH6ecKny9SRoa8YQHEoEMGDBsE4dTuV+0qZP04UKj6bbUefgF9EbB9aj9WoxLjrW9UOLoZ0/7lsadTq/DAU/mYQHOrok=,iv:H3A/KM2+NxlvcsKai1Pz18OqpovRdpvKXpKHE2f8/Yg=,tag:gA6yqjmyra5V8E6PRZ1L+Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
