apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
stringData:
    password: ENC[AES256_GCM,data:nEr3YQaokcVUfIrifsiqIWT4fNuW4TItANxxN+56TfFNb4pICfiDImB6JZjV8EKxdPlCWG3dKr2rBiPB,iv:Q+FIu9AfUkw/Goqok1IojEylZCExmcAq+remfiqQaKQ=,tag:qIrn8gt/2QHoYWK9eqANtA==,type:str]
    username: ENC[AES256_GCM,data:v9l8gpM=,iv:fMdOyWJFIWHkbJ4oEnDpRc3q1s3n184q2EGjHBan9bI=,tag:2RKgwZ2FeWnhb27PG014rA==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxf6lyfrga0ddxltfhtgzvjkvq74yqjypcwxujpvh4grxp30u33su8s52d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGVitoeXJxcU1vcEdrWDlW
            M1dkMTdSNTNGcnhCOVZjaGJFaHFnQTZ6L1VNCnEvMXlPeENuUWVxQ1hiTjllblVU
            K0JuZjNYNVYvZkRnR2VmZGU5OWg1UGMKLS0tIFJGaGVBaFNid3c5VktGL3lnMjN0
            T3owVkJ6eXd5QlBHM05tSDVjZTRRZDQKho0Mz46nrgnuXQVpLB/wS43IR/clXC7r
            c1JGh35W8DhlCHblE+QdsjofuTNAzINomAhu6d3KvJrijcAeqcBiYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-07T18:07:58Z"
    mac: ENC[AES256_GCM,data:yfzUmWyoRoB2V2DAle8qVpha5pbQGFm9lkw69XlQ6nCS2bO2IH5vZKuXTOeirBliXUDnthnivdeFt2kx5GwaZrLyktw8jLvsQxzShmOjkdbRVqNKXnlqa8r9Wn+N1CrMpSBoP1U72WEXhdNRqdNwz86Qn9/E281iY2tAMEjpOK0=,iv:qVlP+qn7zFeR+DIsxLx0rzdWwmQ1iPBTGHaa2CMMRc4=,tag:N6yhkbZBIhzjuga3foQrvQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
