apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
stringData:
    password: ENC[AES256_GCM,data:L2RuCEINkzRI1i+GtmQjRcSdGMexZGjvPAnqYU5GG6FjWdmk0ba1f4wWPZMT3EWiIUVhAdsXog0iPgmm,iv:a0pu8W3pyOyhCBbLT43FaCbxzUsMt7ZR+26Zlc7LEXU=,tag:dU+R/B8Erxv9rqlPVEqhsQ==,type:str]
    username: ENC[AES256_GCM,data:Ut86HK8=,iv:oX0E7TV4seqFGM18ZrLsFK9QmWeLkdVRTP7WgameR4E=,tag:3BmWYsJGNmuUgGOc+XNrfQ==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxf6lyfrga0ddxltfhtgzvjkvq74yqjypcwxujpvh4grxp30u33su8s52d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnOTNpdXZXKzNEd2ZGdnVU
            dElZY1VINW94dDBZQzhXQUpGOFZtdFdXT1NrCjNvLzBhdk5hREhQYkQxbWdybWQz
            a1ZsYzBvREdwUnRuQTZ1NjdxYXdNMXMKLS0tIGhCeWNKUmVMRU1kbVJUbkhGSXJ0
            RC9DNEpudWNaeHZZVkZycGo0SGFjRm8KKHrQXRPkzrxt/Zu/JitDHNOnKfEZLSY3
            EH+6dL1JpS0J3W6xcRCI5UcGUqo+iprJp8j7n2AvkApOVRWVggIxvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-30T18:41:22Z"
    mac: ENC[AES256_GCM,data:NZrgX8rZ7cLdRLntGvw0aonGnvkhwn6hokmWDOA39XMn1ut43CLJcY9S/Hzvo/wLZmuUj5aO6/ZFP2kVPqWeGMd7vZBVVBs2GCr/CYOvuETYrqHItcyZGL0TJpEUycuC8hxwvZ3FVzJU5zXupn3VMoGvmti4lduh/13Zbxf0mzs=,iv:nAuLcVsJrVpyJ3hxyBDtIzkQTud/CDSQ28ZMR7y8ffs=,tag:p7NPiJWk43hXou3cqr56Pg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
