apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
stringData:
    password: ENC[AES256_GCM,data:FtyewpvfVU/U5ohGAEDX1KqSMsM5IsumiKVmLit3nQzpQSAEkxXFOqtH6wmMLZwSlH25/b8eXZu6txLi,iv:dBLzrYxmf76KhZ6zBTJQKrQc+foh/CKf8xFD+CIageA=,tag:SOuGNqAgaMuSPZZepDIsKg==,type:str]
    username: ENC[AES256_GCM,data:xPIX4Ww=,iv:Ai83BrZtjgGyLRhsPU8J1QRNqqjd3FlH7DFiHMeU7Y0=,tag:EJNs75/lCC4RknMNDfdgTw==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxf6lyfrga0ddxltfhtgzvjkvq74yqjypcwxujpvh4grxp30u33su8s52d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2OEpGY1EvU0FBV3lwaUln
            SUhYR05hY25VNUJTbE1mOWFFZ2tEaUZhbHpFCkwwZ3NtckpTWW5qcFREOVhKZk9T
            RE5Bc2pIbFF0UlZxdTJwVTltTE5ZQW8KLS0tIDMyYXRXeEs4TjRwK1Z4UHIvUjAx
            WDRPYVpRd3hqVVdYOXhvU3hjeHk2bVUKjlAYYm/+r9Rve1CZYNOGiXtlg+sipdgG
            zItwxPtJpICVqzoZUzmREdxPfB7D2jd39YGRc9cGJnXJxXic/TPH/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-02T20:52:25Z"
    mac: ENC[AES256_GCM,data:d1TnEuyUsnOF3QEZGq6IteHC0m8BY2a73usb1svz9+BFMNPXxiceftLIiemFMoGaaoWMcL+YfyICSFyeb3w/J8/VwHBC3ZsLRGo0YZlw1sRJs6c6VZk9fNBoU+a4xGkqYrqUEVNeGKkDWruABqoedyX+jo5ZOcl+2+lYHPc1ZuQ=,iv:ajNc8cIxd1L0UsvA4aUDDH7SDCzsqlmMGsI9wmuNykU=,tag:Sx9yDjlwBa3IPx5Pg1MVmw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
