apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
stringData:
    password: ENC[AES256_GCM,data:4FhJTUg4sZO0L9QnwAenn9Ze6Jrpbiop1GMsnjhJ/PHdmn4Wx7HFDwAK9eagruxNVLAc/T49d6EGacNG,iv:J4nNtJ5/SnEqRFlIRNaXUb3pXiWLaMag4STMRS2JGNo=,tag:EItombZMqHEyYrtQJhDOsw==,type:str]
    username: ENC[AES256_GCM,data:KHqbLMQ=,iv:P5HmWMQTVew28oCH1mUhpfcDRrGY1XTPg1KBvHS9iGE=,tag:WkHZdS+Zwy0TpBU7JTNb5w==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxf6lyfrga0ddxltfhtgzvjkvq74yqjypcwxujpvh4grxp30u33su8s52d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUbUtFZjNnMzJwS25IcFpa
            MDMvUWMwbzk1Z3hxc2x3M0pUc3o2b3U4a1VVCmpMMHo2REp6WEFYQjNJVW5tY0dT
            OFN6NGVRNU9iNERUTlRQaU9PMGUycUUKLS0tIHFudXhlaHJoNktJRGR2ckVKNWJT
            VHBMeW1ub3l4a1BqbnZlNDZRR2pidVEKNxyFPbi6P9kk0QRHHIWZviS98/e73zLp
            0XXz8q49sqXuC9CV/IssVt4cphaGEZTw0msQIMwc07W+OdSfX7OjzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-02T14:10:14Z"
    mac: ENC[AES256_GCM,data:AD8wEMp9foFpLKcVVvQJz99XFoX9bWs8m0rsYSAAydNo/VPdjRrMJy+ryTYl/sYM+yK3s3CyHUOLOt3xZYfHTQWeDqtfaGt9ztvDx6puv/Ah7jCTMWHJCIpuwMdtOTDfTa5qE1mSEkCC3K+u0whLT6Pmm39qoLyMM6dz4dzBCYU=,iv:Hw6tMUEDKNwZHLyj4WMya4Ol07k8fUswAWvVE8raCjE=,tag:l9yirBIlmz7sk0ipHFUSyw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
