---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linkwarden
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: linkwarden-secret
    template:
      engineVersion: v2
      data:
        # LINKWARDEN_DB_URI: |-
          # postgres://{{ .LINKWARDEN_POSTGRES_USER }}:{{ .LINKWARDEN_POSTGRES_PASS }}@postgres16-rw.database.svc.cluster.local/linkwarden
        DATABASE_URL: |-
          postgres://{{ .POSTGRES_SUPER_USER }}:{{ .POSTGRES_SUPER_PASS }}@linkwarden-rw.database.svc.cluster.local/linkwarden
        # INIT_POSTGRES_DBNAME: LINKWARDEN
        # INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
        # INIT_POSTGRES_USER: "{{ .LINKWARDEN_POSTGRES_USER }}"
        # INIT_POSTGRES_PASS: "{{ .LINKWARDEN_POSTGRES_PASS }}"
        # INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        NEXTAUTH_SECRET: "{{ .LINKWARDEN_SECRET }}"
        NEXTAUTH_URL: "{{ .LINKWARDEN_URL }}"
        EMAIL_FROM: "{{ .LINKWARDEN_EMAIL_FROM }}"
        NEXT_PUBLIC_AUTHELIA_CLIENT_ID: "{{ .LINKWARDEN_OAUTH_CLIENT_ID }}"
        NEXT_PUBLIC_AUTHELIA_CLIENT_SECRET: "{{ .LINKWARDEN_OAUTH_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: linkwarden
