---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-dns-pihole
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: pihole-dns
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: *app
    sources:
      - gateway-httproute
      - service
    # image:
    #   tag: v0.17.0
    registry: noop
    policy: upsert-only
    provider: pihole
    env:
      - name: EXTERNAL_DNS_PIHOLE_SERVER
        valueFrom:
          secretKeyRef:
            name: external-dns-pihole-secret
            key: pihole-server
      - name: EXTERNAL_DNS_PIHOLE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: external-dns-pihole-secret
            key: pihole-password
    txtOwnerId: main
    txtPrefix: k8s.main.
    triggerLoopOnEvent: true
    domainFilters:
      - ${SECRET_DOMAIN}
    extraArgs:
      - --gateway-name=envoy-internal
      - --pihole-api-version=6
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: external-dns-pihole-secret
