---
metrics: true

ui:
  title: Status | Gatus
  header: Status

alerting:
  pushover:
    application-token: ${GATUS_PUSHOVER_TOKEN}
    user-key: ${PUSHOVER_USER_KEY}
    default-alert:
      description: health-check failed
      send-on-resolved: true
      failure-threshold: 5
      success-threshold: 2

connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m

endpoints:
  - name: flux-webhook
    group: external
    url: https://flux-webhook.${SECRET_DOMAIN}
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 404"
    alerts:
      - type: pushover
