# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: thanos-objstore-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: thanos-objstore-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        thanos.yaml: |-
          type: s3
          config:
            bucket: {{ .bucket }}
            endpoint: {{ .endpoint }}
            access_key: {{ .access_key }}
            secret_key: {{ .secret_key }}
  dataFrom:
    - extract:
        key: thanos