---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: synology-csi
spec:
  interval: 30m
  chart:
    spec:
      chart: synology-csi
      version: 0.9.3-SNAPSHOT
      sourceRef:
        kind: HelmRepository
        name: synology-csi
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: snapshot-controller
      namespace: kube-system
  values:
    clientInfoSecret:
      create: false
      name: "synology-csi-client-info-secret"