apiVersion: v1
kind: Secret
metadata:
    name: synology-csi-client-info-secret
stringData:
    client-info.yaml: ENC[AES256_GCM,data:UQE46m56i+P4pIFl8uzyG0TTgI+mjc508qnMM54Uoyj6OTsOH9hwDGB02d7eqc6vD9apoxGxoGkUTQZ6Ij3OFiMTq5uvP+7ALiuIjEWm+Jo1aayPoA246X8khO/6odZzOOs1Kz4RSveAFK4QEfRKYJHzUKAvdjqbZ6b6FlWQVwMkKEmgpUpmWiNkYXQ=,iv:YRTmo9r6u2+RKDuZgrx5SNq+CFAHIvyTs/QLJ2TI0TA=,tag:BdKD3AfqQz7Oa24ulW0D7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxf6lyfrga0ddxltfhtgzvjkvq74yqjypcwxujpvh4grxp30u33su8s52d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmR3RveXF1dG1ZM3lHM25j
            V1lQQzRCc2haMXczbzRYOFgrRGNsWVVhV1NJCmpINXh3SHR5Vk15cGxRTGl3SjlB
            TnhuWTdZZncwS2VHcFBwL1k2U0xlL1kKLS0tIHRsYTJRdHo2ek04UXpndTNyRzBW
            Z1pLTVZ1cnVtZmNpWncwWmhFQVJQYzAKjMTZdCriRyKremCdqMGTLmwJpLZ6eLEF
            +FOGz+6QiwhfHxnYbJYpHTFofqezSNZqFlb5Q5YM4+LmQNamNo1pTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-29T21:25:14Z"
    mac: ENC[AES256_GCM,data:cfioxA58I9G7qsgtrWmwdUpWMdmM8Xa8MIAtLjjnkSS39qfZ1aP7kS8nmfH62Etm1DLnTTw9ilWBKxrH8Sh/MduNHMrVHqvlCLHJRt1pakxF5wcIbGZyY67zerGsltwHsOh6Hz4YwQOTxc1WJ2KmwaiBDwBRmugB0yK0eL6Oei4=,iv:lt4Y/Y3LdU5V8pAXv6DjRT8DyY+VOGmyAoEbNRTAG2Q=,tag:qR6ah/O60bjQl0s81Euaog==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
