apiVersion: v1
kind: Secret
metadata:
    name: synology-csi-client-info-secret
stringData:
    client-info.yaml: ENC[AES256_GCM,data:tCpq1TCR2hhgnTcAz82fYGLwD2FJ7f/pVVWDyRUtOGJcetxQffXxVM7GVe8HfqhuFMxmCeaNob8KAnwJzhprCtTER03LbYUkLFoRpxpTRpgEFuj0fdg78VbxgjQQHWj/lzOlSfPljlxxEtG3cbpd01yvZpQAwuP7uOTeuZG2axt+roLKa4uTsg==,iv:2CND1sO25CTo/uYLOHAchu+KSl9LloTiOB9c8BWY5bc=,tag:VmLyckvWxsz2spJfBGMuPA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxf6lyfrga0ddxltfhtgzvjkvq74yqjypcwxujpvh4grxp30u33su8s52d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMld2ODlJVFpkd1NnQlhU
            dmwxZHZVWkNTTysreTdzRi9oUTVLbWFPV0g4CmNRbFVUT2FPc3NSa25OalVoT3lO
            UklRb1IydlZ6eXJPaWtsc0ZjVzJEaHMKLS0tIDF0STdsSDFoN1hjTGd1MWVKWUMv
            U0xOVDdjcDJJUzB2YkJKUFFKNE9EK0kK96HK+k+AbQSwIoOTSI8MxjrZnz3aSjwf
            CryVcfUbOIJHTAqYDPkmKUeCsh1kvgIWNnpCPi4wpMsCBW6Pqk5EOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-30T21:10:36Z"
    mac: ENC[AES256_GCM,data:nHNpq8N3ACGETXKWOm67AZdODaq4hjv+EMCRwvmI0uVSDrXMWW1SRpeBfmP7B6wTUnjeOSFaAQ90gsbbjchFIDGg3JqZV/WNB9d/yICR2nMOxcya9h9W8e+Nwq2Xj8OREXIpy75TOvTGplEQtiTxVqqXgfDihD63dPeLOgwQDdY=,iv:xBw1DuvFhlRVc1fctdcF7GFGNw1XXeqAfGOluzW5G+U=,tag:C+92VD20udBBugKj0yfkTA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
