apiVersion: v1
kind: Secret
metadata:
    name: synology-csi-client-info-secret
stringData:
    client-info.yaml: ENC[AES256_GCM,data:zmS5SJhWCdY9EjEGRO5LZsuVX5B10crOkDbmYjNbGp7ovt4MNtVVmj9kUBhLM+BTbgGZi40391H+VHB10laDbl5M21h/3c/mJSgyDyUZT0uql6L0aDotDEyun2cuOPCtdabIuHzqAJudMjgOfFcpDT3REG2ZXTyVnAGgvodAcjprEPSHYbVNKA==,iv:d1Wu7UF8Y/iucaRpPv5gkP7/NoClynbMxEpz76bNHAw=,tag:bRv3g+hDayszFFFFfSPPEw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxf6lyfrga0ddxltfhtgzvjkvq74yqjypcwxujpvh4grxp30u33su8s52d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaMU5OYWtveVlXZnphdWdU
            T01qWllkVmZyYWFxdEMvbjhyZTZ0MW0rN1E0CnRPdVB1QkUzNENjU3A1eUlIbU9r
            RlhaS3QxUDA5SHFDcXhTamJXYkNLUWcKLS0tIEE0TDFyelRZL1B1WkRRQU8zRVJm
            Vy9XYWlDTjVFbWpBQ00wL1R2REdqdjAK924SBdRy4BdePeegsAMn+BDkYdDv+MMD
            je2ARIY+A04gistOhirb/IRjm0U68ZEBe5Pnc/Zqz9f8Y2fdlGaSLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-30T21:21:27Z"
    mac: ENC[AES256_GCM,data:Covos027ISTc1blBP+t5LAGEMtqqYqXjDJjo8KnFVSgUdgf6Fr7uR139ye/sLIR7rIPd0butYx/XjG+mQCV1bVjrJMg6oTN8c9yoeh4lNtwIklj1dyPWfP3gcE1SKG2YCCkZtW4FwXapjZrl7azTSPl8luf4EnFiiNmLcKpOlUM=,iv:I1OT52sQed7eVoIuUZN70F/xHb2ry4G0/MGAeX3ouIA=,tag:Zw65envUPcMFDtaeOxmdLg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
