apiVersion: v1
kind: Secret
metadata:
    name: synology-csi-client-info-secret
stringData:
    client-info.yaml: ENC[AES256_GCM,data:jzki6TafefESgQDc1A+Txez0LDKxyvv0jCJpcZ0ivqrWS9e6x8yHWoEjbPxED6UTJqUovbgii8FrbwC4e46bpxdWxDxXHk6aG90L53n70+N1jfeh3g//dYY2nDY11AkMy4J603p3T8O9SsKSMwB9wj6eZTr3tKzKSUMdcmO2j7SzPh5i7RYimw==,iv:56YW7gw4FdklvqLxjSTj02cn2A3G8fJhCVo16kYgnhQ=,tag:Pq4+59eCZTpPc9bevd2doA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxf6lyfrga0ddxltfhtgzvjkvq74yqjypcwxujpvh4grxp30u33su8s52d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ZWtNb0VhdzhKZTc4ZDAv
            L2Y4OU9kKzlrSThuSDg5UTRkemJDUFc0SVc0CnZPUGRkYjRIaGw2MzdjSkN4WG5q
            MkRjRysvWXd2RVZDNFNwQmZlVEdDc0UKLS0tIGxUL2tyYXFoa3RkWWxWNHg4ZnNp
            UFNmNE1MNVplSGk2cjVzSzRoV1dhZmsKiw2a72h3a7eLfmjiPABCI9H4MFI/WMwN
            MGGONrh5ZBO9dY3hFyJDoFFeyD+ABUgjnuUwNreYx1LPNwUh+A0k3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-02T14:10:16Z"
    mac: ENC[AES256_GCM,data:pPmb/wmows/TRjoljn9LMiUBCyNCbtTIScBw6BCB4PnTOgAgS+CkeWh0h6LQALnMd6Dkvnl8of1GWsw9X5ivCnHEg3MyaFZOS9OaNAoKXsdA2q7e6cl8+p1JzblgovwDdIDSD+x+Jq96nxnopHWhMRLd16+tF7o/BM/LOfcMHgk=,iv:7xtj/OLx7Y6GWvtODablO1LT/W/QdtDirgnXeiPyvyM=,tag:UepVQVyb6FbrJoIRUPJvbw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
