apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:ZdlHVe3njAVPIGlSyXJnw+k5Zw==,iv:DWuDl02WLneZxue4BlIPXft+g+AE5HJ4xECb7hH71w4=,tag:yzVBjE4vprfDV+/bcaOhhw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:6XyE2nu24UlB5apbGFGTEL/K22aZbvK5N+SGS2/c11Tu/b9x,iv:nT3HbSRtqBc/iCIibzSwJHYqUYZg7WCk8Vf1nX9zTRo=,tag:9sI0AdM830LBlIBVCw/38g==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:i/OK45ZwlzSAEgM/LA==,iv:hjy214bW4Ro3olv0aMLmuc/rSEHCwAFctjd5PR9M9Dk=,tag:J9vuMzIPV+OmiUOpYxSVbQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxf6lyfrga0ddxltfhtgzvjkvq74yqjypcwxujpvh4grxp30u33su8s52d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQdUs5K3dUZ0s5aGQvSDMy
            cVl3WGxQVmRWaHFTWjRrMThNNm0reTZ0T0d3ClZyNFdudUhLdGhMYzZPQlRaMEZo
            aGxkeFd3OFRWUDR6NEptb3B4NGUzTGMKLS0tIHJKNVV2Z01JOG9zODdzUGtIWU1x
            dXVFaFZNbXZFOUpTaExsdGtEekpoQW8KNFzST/JF1VbIFYivBaShHNQOIkCDPVsO
            ilcmxCFAaAxeVirvo+2cDBn4oqU860upkudGId7e/5ircmZMvv8KFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-30T21:26:52Z"
    mac: ENC[AES256_GCM,data:RTJRPNo/DVY5tLstKDStEOpI2e5f8ueGmlfqLFRTh4Y1rQJ3g8BOVnQkDSuX5uW1aVLda3MO/jPmjzyIEYyCRiihuY/pdT4gpj+fNrj8tBswZcSzL1D1FlXWx8fU6DAvj6/2GWfIGqUEI61Ve+e1cjGE8m+yW6AZE6nL4P+IE+E=,iv:/eODq7m2sBgzlP7cORDnlJJPmfXx1ZshqN5gTGUoJ3k=,tag:2cBby76oOI89ALGt2OdFHA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
