apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:Ts3fpCO/L5SZWA90wzHeEnQ52Q==,iv:DUyeq0EikNtQt0ss67ptkLd75MsgaQxRC4WjQh2IAaI=,tag:z7C0hrDAzWKIOkGrjsWbNw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:2MJrdejF+AgNreF5G+iceEoYzs61rkv94JXD0FjeprSzsRKG,iv:KQPhqpzJqRyY7BpLywH3i9w4xktBtif5xSg4KqcWSOQ=,tag:r7aOyD+R53KOp0mqXvCUoA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:0exM3WhxM6gBMLnVCg==,iv:k4pRfe4gHR7hJ4U+srQ+11rA83rV42zR6MTjfPNxD3Q=,tag:ZkSjmE1xbt/RXl17Bpvl+A==,type:str]
    SECRET_INTERNAL_DNS: ENC[AES256_GCM,data:En4qUeN8lKZ5bw==,iv:/JQfu+HRPjevuiyfw4PFZeMn3RlNijvw1DD299gDMQs=,tag:ITdkNkodem1IXIEomLsMJA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxf6lyfrga0ddxltfhtgzvjkvq74yqjypcwxujpvh4grxp30u33su8s52d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiYlZSeVpiNnB0NWt3Y2pO
            NzhKSmwwUnhoampqRWEwbUxDd09XRTJBVGgwCkJpQWQ0K241TTNWbmJOQTZGMFJj
            Y0t2R1VDK2pWZEpOTWI2ZTQ0SWd0blEKLS0tIGhxcTBCc3FFZzRqd2RYempNUk9Z
            amNwZFJUY01MeitJQVNBRE9tR3AxTGcKwv+vzuCZjYLU/0CHJcdl8Tz3YV3APFde
            jo+ux307Ha2rVX26CA3GEjd08XPWTcKUa4AjUupMHrkjMSbOQZY+HQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-07T18:07:40Z"
    mac: ENC[AES256_GCM,data:u467SfdQQUP5TzDU3G3AfJ/Yf1RtYlP4IdcN+wcTseUEuvB22NgkzupAWQTBA+aIe2a6jW1Ioj2SbD2CwEit++HmmPcynq9y+JuEhIAxLyP/A/2HN3vp3PXh0NlxT7vZTUfXtBT6CWzUFCnR8bP4/tijg/yL/ixLoXKB7yEs0YQ=,iv:/JxrH32/gA4CJeJMCh91jRlfR4uTbS7HtdlyLeR36AE=,tag:Cg40jsbsYV2iAXeDXTYtjw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
