apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:SC6iaE7URTM9KgewNoPFMlNL/Q==,iv:5cgdG5hZsQGNOpI7ucivR6Yoko2zIqT+mM+LgTxknLU=,tag:zezXxWXVccPbXI4Ld/dqcw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:2VBTZxdQNbUkZmkr2KXGSYpCSw6h0xYE8mwlcYrhjWdnlbo5,iv:aeR0N57vY/2bQDQfzci/MKZ1J3jKPt9s11+vfEMvkSE=,tag:/7UXjl0rbBNjlQ2zo2Toqg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:YqirOh70vs4faM5guA==,iv:nfmSIR3IfQLPQrF7TToro90mykj7yOVAgmVuaKBC7Qw=,tag:toFI8XZHTkziTNVhl8Uwxw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxf6lyfrga0ddxltfhtgzvjkvq74yqjypcwxujpvh4grxp30u33su8s52d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWWGxRSTJSeStURG5veTVY
            VFBpWHVwQ0VqdzZaRTBqeG12M1FQZkQvWUhvCjY3RGQ5TWo5UWt2ZXNMYVR4RWcw
            TlNmSHVzSEVFOWFPQVpkZG9PLytxSjAKLS0tIE8wT0lFZzQ0UWNBRUpmLzFrcHRQ
            NU5OMW93Znk1bjFsU2JVb2JRcFN1ZDgKsE3HVSvdsM7fJIZ/cJ6IOw0DNyhueL8W
            ydjFhlqdsmu56lYlE2C8qsz2gSmiDJICvitvUtwGIGw7BxUD0oF6pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-30T21:10:15Z"
    mac: ENC[AES256_GCM,data:RQT0J3KUFGWGCBLpKc/UyGF7bTkzDiAcSkc90b3CfrYnmbyRPPc+/09JmmKFb1yugRPDzs89gwBTF8292rilEzaQsOvLT+OFMa3K5aC3wkHAgE+ZvhXZ/7VnMuyrA6Jb0HC17GUSY8wynoiyk3qmZ4WXdYbwjuVNLqskdEwrJ2Q=,iv:LYfRESP6zgfDQZ9ToeED2eeuyb4ndzJhG69hr6LUwTQ=,tag:An/Djz7eoWLHPcgBHGxnFA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
