apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:GGPZz3+dlsaQbWSv,iv:KEusTE5N2Fd21hxH9T1YHLHljupYrbYEwX1xTchdcVI=,tag:m65z1+ipWo/z6qqMU6LSew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxf6lyfrga0ddxltfhtgzvjkvq74yqjypcwxujpvh4grxp30u33su8s52d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzc2JYS0J3M0JyVTRHYlds
            eFRvMlkzOTZIVS93NmFvQXAvTFlSQjA0c0RFCkRmb2JLcDVVOWQ2MnAwdTRKcnp3
            dVB4UTJGalB5WVYwUjhTYzNnS2FsaW8KLS0tIE9HWksza3FiMHUwbjNVQk9NZElY
            SUpLVDNPRmlzUmZvcE5HaitsOGQ5M1EK1KTfE2ngasbjgzfzFbAKrHH37JZJJxsH
            5GLD+5PgWT2Xo76PQRsFTprUEgZTx9ZK8VYllNmUNqAr4Kd5f+8KUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-30T21:26:51Z"
    mac: ENC[AES256_GCM,data:t4YftjAzRzlQiCCrR9M0NBj0SqAgZ7zzIYW2bUyP9/oNhfEjy2Uui877bAv62ZlU9j76Wlxpm0BADb8AoAAqolCHSwWSAaW2iaQoIoiKUzPIhCUo0dvp9SyYizk074FCSjyx/EI6ZoCOAQ3VMyeroY1wZvZc63yH4xgB7QW+AYY=,iv:5inUJ5Y5cQPMrxJRYqCGjvt5zZVLzSbThJJPbH16gv0=,tag:rmsrKbHbS0YcE0JhVbIOrQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
