apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:qeRlsS4WSjTzX3WK,iv:V+IGu9r9bIOPobtSP5Rlnq2cIXWqa6J9KSUQSOS2xEw=,tag:DHnsH00Aa4/wVzfthUolFw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxf6lyfrga0ddxltfhtgzvjkvq74yqjypcwxujpvh4grxp30u33su8s52d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNmlNaFVRK2NiNmsrZjRk
            OHAzcXJsbXYwZlVHRElhT050V2FjL0VLMm5rCldQWVJVV0NRc2hVbGhZbEpWdDhu
            aW5ISC9Nd2hGdVhRaEprTTZicTFJWlUKLS0tIDlhNVJIU1I2cEFDN09HZHpwc3BI
            b2lKUUc2cXRpenRSTTNveE5YZ2txWmcKceskDwIythJ7xajG6AuUwysZTVU0ossq
            nbIBHaiyV2DKKAUZuPstOtYC4rhaSwJW6xRD06If285H+KVaaiF1uQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-02T01:22:13Z"
    mac: ENC[AES256_GCM,data:rdy0KG7cGtpU8AcvWAL9Pw7mzV6BCDiR//KleJG7olbl+4EvP3VOj4OH8KmsVvKdb97D18jMsBpNNNGsHu4VYYsvL0YezyvO5wKQ5gyfJ9sNeUImKy2r3oHgSz+TLCbmT7TqvoAGkKTaAzlt7grGz7QC25bGj+dBtXJO1wv7jKc=,iv:O7UazZfLJExHhxwweclZj9kuXnPsxctP0gfwxer7k90=,tag:gtRnkAsLHdd7VURER/akOg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
