apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:eGvQY/lDuO16YK5YWwqMDMvSAw==,iv:3+4kQqWTd8Y4Wm3HVLyKkUgX3vuaKKew+I7mOJJrcBM=,tag:eIN9i21oEbwU5nWxN5ajgQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:6YQ4s9SQk2HDjEn1aGo7jyOUBe35d6jQG+MAg1f36eklhNIN,iv:ljvdkO4clDGfep+tdK+uFsrsfPzdK5DN0e4GQb1KXvE=,tag:WMiIuR4P/c+A58qmgWyqXg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:UFWVsW7xH8hsNY5ICw==,iv:cklATd26gOWRq/GFo4C/n8jfAW0LyDeThDss+e3YxWo=,tag:g/duCEMLi1+cAXiYupGEUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxf6lyfrga0ddxltfhtgzvjkvq74yqjypcwxujpvh4grxp30u33su8s52d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpa2tOOGVhS01JRXlldEpO
            WXhic1lkYjVyTFFmUEV0d2pKUzFpNzJEcjBFCmgrL0RETkJTZkVSWXpRV2lQc29y
            cTFNTjJyZERBb1ZiUDJJVEpvQTQ5R0EKLS0tIHN0SUtMOWkxTzVqeERiWUpzRWRi
            NWlZSDJibHh5M3Zsc21tZnJhWnpvNUkKuRgr5MFk5CmuYF6qNy8AXpIe9Pt1JFyl
            ebGl6Ova4dbm1HpCrPsLQCd/Ubkegtje13qRzQ2lFls1q5E21vJ1DQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-02T14:10:00Z"
    mac: ENC[AES256_GCM,data:+fbG/bbfUldHioQb6qBEVxywOFWyMybEmJDh1/MdKChIw5bLQhVQhwRXXbhf8IjY1hSe0BNPpJbdC/K6NJfT2zCs6YHnHMduU38QJttuywbypqXPnr1zK7OKFFd3ysNUXa2rdGm+y1mZFOVmTSePLsrvbvdwGX3rQqwAVSIdTzE=,iv:nocOithi/ISp2F2ofP7nzLRcR8uKH9w7gbkl8lu3KBU=,tag:o+1HskViQHkiedPcH0jssQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
