apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:lQ1yQq0jNerJ9/4b,iv:54Gva6haOsIt5QG6wX3uz6Jf7ceu8Fv2ttaK7/HHbi0=,tag:uQ02A9XFurtWZG9iQNNq3A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxf6lyfrga0ddxltfhtgzvjkvq74yqjypcwxujpvh4grxp30u33su8s52d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZGtndUJWRWlub25XMW1T
            YlZuMjhFQlFrRTkxNnhpYm9PVlpxWWdRYldVCmpLbHRuSUk3NCs3NXFQOHdCZkYw
            cTRJelYrdkZVQUYzZGZwSitoc1lQbU0KLS0tIFh5Rmd5bnBycFRqNUtjWFp3Rldj
            eFR4aDJpNEZ0eEE0clMzcUVOdWx6NHMKWt4Yzwz2Dm1xr0E6mT0RGxDHlRxNyUYA
            tnTTA5qVGDjd5v54KNEsHExPFpgQXPVA7tstxk7eKlx/apdQdgLNng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-10T15:46:14Z"
    mac: ENC[AES256_GCM,data:MsetMQACG0G0ezRU1pGTqMw5gQWs2eX7gtA2tCuk1AaB1a5wQ1yIWLgAdWO2zenJQuFR5r8vUDQqdBtXiwuuN/2n0rkpq6mvVOWj4GLyjsg/wL2MRQC/JEAdRyy+hk4MzyV5mplkyBxglO+x+QUdqHKIhHNqbeZE3FZc1dpU8fk=,iv:uqOb5BNOWt3HazyOrI8wFhJYRUBlww9hO9Z8rtevtd8=,tag:IfaqjjMO/YOUdmpGXliNrg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
