apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:Oj5inGfFgPyMlOKROu4lLfe+Yg==,iv:4vebo5cEHdddI1q+xbI+3YkughlGktdT9pAK7TKgkr8=,tag:yKTjXBTqQsPk5Ni9LE5p2Q==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:rtp1JX5LFy1j4COZFNp0xrUepzQX0RDSw6PXJIwzcz6YJoUR,iv:LcDlTu+KLKPYpXiIQoNoV9fflx3Et9nCmnAx6fxr1ZM=,tag:sLdOYUlmL30RNxfpIEp59A==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:mjSR28EEfFBoh2sdSg==,iv:7IQv7oQoV+NUIZUR+/a8qFA2fpWf5g7S2XxUZh/7mrA=,tag:6U8owBnhnko8jrOk+tcpNQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxf6lyfrga0ddxltfhtgzvjkvq74yqjypcwxujpvh4grxp30u33su8s52d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDUEt5d2o4K3lkM1dGdzhi
            MnpYOEtaUzg0NktWOENUaDE5dU9RWFUyN1NjCkJqTzE2L0pGQzhOM3Nkd1NUUVU1
            L2VZQXphc3BObEx5RDg2WUUyTUNDeGcKLS0tIEkvTkxMcloxaVpKUnZMMHU2VmVE
            WEpoS3JhK0ppYkdlL2VQVnkwalJLQlUKQ8+MfmceiAPmxDCcjfOfEm+Rkr75+S6A
            EiJOVG+9jdY+gBy+0SuzE7IWzESGI/lk694gFyIpyi7Scg7Yn5rjFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-30T17:14:54Z"
    mac: ENC[AES256_GCM,data:Ktz8YDVx4aGvGOSnKmhBtqWfW8a30o01Isg1k+77gfdIG4N6Gh0h3278UU2G2pkVe3nKtzYCk8BOZzxmVGL1/NIK5PZX2bE0xA4iUxKFq5zcKHarlNX1GnYP+I0rLGrNSsPx2qeQFBFsGifagV/FPNdxJzFdnm5fLHgsVwYuVEI=,iv:ZKlHCEXP+ufOl8L+UAyeqwAm5uyHxy9Ppy6XlFBK9eo=,tag:0/Ivx/YoF5YXfz5CVwkbuA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
