apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:KG4/7vyis+6nrO9b,iv:WSonPlq+co+1iZtJ7ADCOba3xiOJKsb9/69bNH/t7pU=,tag:9WL3uI43Xb7MEnaEiKXV4Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxf6lyfrga0ddxltfhtgzvjkvq74yqjypcwxujpvh4grxp30u33su8s52d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYVHNISjNHS3BtUEtRRnFs
            L3Y3cVMwQWd3c3ExbWVLa2RpNnZ1dWRCL0RnCmYxNmNxaDNZUndRWHF4cjhjL1N0
            WGJ0eUgwRUErektJdXRYWTBzdThkcmsKLS0tIGs4L0FFamkxdEZOYUZoSzBQSitQ
            WGJXTko2YlFjZ2JvS0Y3M2RBVjB4ZkEK1F6SRfVNoBvDXBuJz2YOrfNU8pFslznV
            odnM/c8sOI0G3Ye1RGPdu3k0xb19uI9hFVNKfMiQgzz/g7YhG+756w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-30T21:10:14Z"
    mac: ENC[AES256_GCM,data:JaIPufZnDqFQ9mrUsBhJDF73JDDv8cPznBsgWPAGjOwsux66e0aa/KBzPOEc1zR3BexK1/Q1UieQKkrePdZl5Ik/lVDkus8Pk2qHH9lqFW8GPo6TwOSgX4ujz973XSXatYYHyrOeqFsXOzHC/IE/9TbQaltISE6jtDxMRMUTbiU=,iv:fer6+uV9fNhWxgG06qIYpeMzrFBCTvMYnXakrKX//AE=,tag:qSwc9dzcOenLQAuAPLwQkg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
