apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:guIu4aD5BfwmnbYw8nqTV3FX5Q==,iv:6gg0Xc5aNP3lN1r4ihehYFD9NgOj1PmV2uWV/ZgCpLQ=,tag:zfNuDoY0s3P7Pky61osRWA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:45gFg1GDsG9DYIMOr0OQ2YoXsUi9UD5YNUq4p6RZG1frPQu6,iv:YGLItv0XU6YOZvYs3FaEhrA3Mj1HIsY6kfJWcnWsLY8=,tag:eV0ipzOwZHQY2XxRZGNrsQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:yJEA5XHVIWoiHvfl0g==,iv:E6QStrc2iwsfa5aXCE1zNhjZKGC1/7UzY8pvVGcWaek=,tag:btDOyhPZJjao8hS64WwHlA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxf6lyfrga0ddxltfhtgzvjkvq74yqjypcwxujpvh4grxp30u33su8s52d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvdW5xUG1WWlYzZjNrYUxM
            ZVI5dFMzbEptTTFxODZXdFdUYVdab2grbkNvCkU0UzNFUWRHRGdJaURqei9JV1BS
            U2ZUb283clRCaXRVT3lJL0FYczR6OEkKLS0tIGV0TFluUS9FUWd3MC9VY2dMNEFm
            a09XRXJ6Mm13Vkc0MTZvZUpHUEVvRlkKIIzRoEI8GZNYK9ULHPOX0XDVTzPSygZ8
            ExU4cRJ54caobH6LnLNYDNiBUv3o9Uhh8Uktmo7eZKmUK4XoFOcMQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-02T04:12:07Z"
    mac: ENC[AES256_GCM,data:9sHXZyibvloeQuCvIgFDFOTYu7Ym8LrPM6ol54Xmag0YbuScud21CtDfKaNMTT1JnOng2WiyfjVHONjlGAZIBYZxKAj9vIJfhCbn12L/1LEx01sVQIc9mCHINvM/UDi/5A8/jdcRVmIdRgpZUZbmpREeAQVSXQxuXzzh/S6R44g=,iv:syD1gWpgqT8gW6SrNwwto6ClT62BxT9lqStsyrExnxc=,tag:z+s2HrNuL1l2cLAs6uaNPg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
