apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:ybIWSVBCmL98sdPk,iv:7HNPWOACsfdT5I3m8k4UBgb164pAy0Eg44CA2Uu8GLg=,tag:NxLSOoFnYiOdrDoc9U+YBg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxf6lyfrga0ddxltfhtgzvjkvq74yqjypcwxujpvh4grxp30u33su8s52d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCQ25zaXJibm1wMk90dmpt
            TCtWVUZ5Q0FVV2xTY0hvN1BOWDZ0SkNRUUQwCkxTNm1acTI1Y0NWamZZTktSNTEz
            SzBaNlB0cVljTi9hSUhxdFFsZSs0cEkKLS0tIFRKNlp0RFBwVERoY3QzMVdSekNI
            ZGYxOGM1aThJR2Eyek1UckxLSm5wRkUKbtJtqJdlXyH9PuNOa8wi+mld7tHpJUN4
            gKhabhmnoVxa1kGJrd5VG/KsXsWmuWLuhZKfNSCwOamOYiEX8sGO7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-02T04:12:06Z"
    mac: ENC[AES256_GCM,data:OgoxQClcxbjWCCMjEe8EzMcoUrQ8KWvw6d1OQgQZ6rFlbcdHll3uPjll/oXtsVw2E8CBU0SzxG6q4Mu0KyH1l7pANIap/fRc28dSf7cX1hdUXTd0yMrytu5mtJgr3Virj+SfHq75oQnuDCkewjLhKyEZTRmYRgpXLqlMS6zBvfA=,iv:vw5hvVBTooj3onAyNi6u358NBGLn6QS8ZzHOoYpeFvw=,tag:22yulG69auLn1RL7nD5s+Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
