---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cloudflared/ks.yaml
  - ./echo-server/ks.yaml
  - ./external-dns/ks.yaml
  - ./nginx/ks.yaml
  - ./pihole/ks.yaml
  - ./orbital-sync/ks.yaml
components:
  - ../../components/namespace
