---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/observability.giantswarm.io/silence_v1alpha2.json
apiVersion: observability.giantswarm.io/v1alpha2
kind: Silence
metadata:
  name: etcd-high-commit-durations
spec:
  matchers:
    - name: alertname
      value: etcdHighCommitDurations
      matchType: "="
    - name: namespace
      value: kube-system
      matchType: "="
