---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app snmp-exporter
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: kube-prometheus-stack
      namespace: monitoring
  values:
    controllers:
      snmp-exporter:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-config:
            image: &configSyncImage
              repository: ghcr.io/onedr0p/alpine
              tag: 3.19.1
            command:
              - sh
              - -c
              - (envsubst < /template/config.yaml > /config/snmp.yaml)
            envFrom: &envFrom
              - secretRef:
                  name: snmp-secret
            resources: &configSyncResources
              requests:
                cpu: 10m
                memory: 10Mi
              limits:
                memory: 128Mi
        containers:
          app:
            image:
              repository: prom/snmp-exporter
              tag: v0.25.0
            args:
              - "--config.file=/config/snmp.yaml"
            envFrom: *envFrom
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 9116
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 128Mi
        pod:
          enableServiceLinks: false
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: *app
    service:
      app:
        controller: snmp-exporter
        ports:
          http:
            port: *port
    serviceMonitor:
      app:
        serviceName: snmp-exporter
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s
    persistence:
      config:
        enabled: true
        type: emptyDir
      config-file:
        type: configMap
        name: snmp-configmap
        globalMounts:
          - path: /template/config.yaml
            subPath: config.yaml
            readOnly: true
  valuesFrom:
    - kind: Secret
      name: snmp-secret
      valuesKey: values.yaml
      optional: false