---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: thanos
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: thanos
      version: 15.7.15
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: local-path-provisioner
      namespace: kube-system
    - name: redis
      namespace: database
  values:
    image:
      registry: quay.io
      repository: thanos/thanos
      tag: v0.35.1
    objstoreConfig:
      type: s3
      config:
        insecure: true
    existingObjstoreSecret: thanos-objstore-secret
    existingObjstoreSecretItems:
      - key: thanos.yaml
        path: objstore.yml
    receive:
      enabled: false
      networkPolicy:
        enabled: false
    queryFrontend:
      enabled: true
      replicaCount: 1
      config: &config |-
        type: REDIS
        config:
          addr: >-
            redis-node-0.redis-headless.database.svc.cluster.local:26379,
            redis-node-1.redis-headless.database.svc.cluster.local:26379,
            redis-node-2.redis-headless.database.svc.cluster.local:26379
          db: 13
          master_name: redis-master
      ingress:
        enabled: true
        ingressClassName: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
        pathType: Prefix
        hostname: &host thanos-query-frontend.${SECRET_DOMAIN}
        tls: true
        extraTls:
          - hosts:
              - *host
      networkPolicy:
        enabled: false
    query:
      enabled: true
      replicaCount: 1
      replicaLabel: ["__replica__"]
      dnsDiscovery:
        sidecarsService: kube-prometheus-stack-thanos-discovery
        sidecarsNamespace: monitoring
      # stores: ["thanos.:10901"]
      networkPolicy:
        enabled: false
    bucketweb:
      enabled: true
      replicaCount: 1
      networkPolicy:
        enabled: false
    compactor:
      enabled: true
      extraFlags:
        - --compact.concurrency=4
        - --delete-delay=30m
      retentionResolutionRaw: 14d
      retentionResolution5m: 30d
      retentionResolution1h: 60d
      persistence:
        enabled: true
        storageClass: local-path
        size: 10Gi
      networkPolicy:
        enabled: false
      resources:
        limits:
          cpu: 150m
          ephemeral-storage: 1Gi
          memory: 320Mi
        requests:
          cpu: 100m
          ephemeral-storage: 50Mi
          memory: 128Mi
    storegateway:
      enabled: true
      replicaCount: 1
      config: *config
      persistence:
        enabled: true
        storageClass: local-path
        size: 10Gi
      networkPolicy:
        enabled: false
    ruler:
      enabled: true
      replicaCount: 1
      replicaLabel: __replica__
      alertmanagers: ["http://alertmanager-operated.monitoring.svc.cluster.local:9093"]
      extraFlags: ["--web.prefix-header=X-Forwarded-Prefix"]
      config: |-
        groups:
          - name: PrometheusWatcher
            rules:
              - alert: PrometheusDown
                annotations:
                  summary: A Prometheus has disappeared from Prometheus target discovery
                expr: absent(up{job="kube-prometheus-stack-prometheus"})
                for: 5m
                labels:
                  severity: critical
      persistence:
        enabled: true
        storageClass: local-path
        size: 10Gi
      networkPolicy:
        enabled: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
