apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:uFwKzbbxJxwqXDvW/dX/fBfHss5r8zW5QWY79wqXDpWyMvxw,iv:BaqslWWPqpYuGgxS/BB8RSuEMFnd9oR5eOBdb8ajk7c=,tag:ZR0axWiHNnLtCIsbi/hrjw==,type:str]
    credentials.json: ENC[AES256_GCM,data:rz4TemnjW8eKzLLM7Jqh3C2p7Zt37Byw9Kip0qVW2UZU2pWleQOG+97YgeV5v59pMARzHmir1ILAxr5brdwWEtV3EkAFrg3TFUtpQMAINidj2WFMhl6WdCY4GZG1hDJz3B9qrr2b12qg7itXY5U90099CxJm3hCC3IlxXiyZ1ORjUsZl42I1cwXd95ipv2q/WpzVJ7hrP4XrkXCvamznBwmIx64djOccDB1lADuLGA==,iv:9ZfTwbcNKM0DjGT7ZetTjYma6HBP+7aofyRel7WELuw=,tag:SmwiLUNWQJKe4aozWLr8Rw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxf6lyfrga0ddxltfhtgzvjkvq74yqjypcwxujpvh4grxp30u33su8s52d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtVUxkYjhZZ1I3ZFE3UUhF
            d2IrOWxQNFVrOEtpT2FKVThsUHNRNDR2Q0JrClRya0FlTWtIT0ppZVYyRU04amli
            djNlM2R2VG4rWExRZHhqclE2RFZtNVEKLS0tIEQ0QVExNE1lWTRMZmtxU1Jmb1lJ
            aEtjYVk4NGZsSFdhd0RxZDRHU2IrS1EKBewC/ArTNT+xmiXwWAaCfpr8mcmLTUYs
            RhR4O4JpOKtYwD/GS4hcGDs6qN4t7hTkzFT0WWCIvDqVuiKEdlyTmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-29T21:48:10Z"
    mac: ENC[AES256_GCM,data:kBcrPJugjkceDaiV5pYuIG51ghzwN46nsE0UAevJsGOQmxBTOaRr52ROHVy3MU3S1YO8Ub2qutEI9GuuGztcIvh1BsMXp/Xrx6nXQN75lImSkyEpi9bTcM3C45B841J6ntnotx3QLASLcDNtUPh1boZw/mP919QnrbfNHYaU17g=,iv:7yzaQCcMUifTB87/eVQ76Uqsg70L1BNBFAq5rJh7KeE=,tag:bVMpuz3Rfe1w9j0ZI1vGbA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
