apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:ixIPvi4MQhv+7vJYpihpcwXNNDlXC3t2bwnYJloc2WvB7g09,iv:/apXXl5H4JYqOE9yPxY9viLD3KQIQF8qDdfq9Sg7Wss=,tag:d1sztPfAwAS7xwIynBE3wQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:sN8Zb2tsbL4VWhhvffVRoF35bUY8z2/1k2U5TC0e/hBQFppUIUYzvy0w6ecYmRhH7fKHN070ba5ZPrd0q4T+DkuToGsJh+10ThoFpByOcow6nfX8xEHYzwXur0D66617yVaHndGa326P67fKo6ETLkNsZqI/i7Jr6hLI2vrsSMM/7dLDEMnMGXaBwff8EgvRUI4S629/yjJbPss7o43ptce/jF+Z0+KPTs2/wHVjig==,iv:eJw88hah2pA8X55DBcvCTK2/Zt7fW76SJh0HYRClpg8=,tag:CZzGMjQWU4+IP+pMPU64mQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxf6lyfrga0ddxltfhtgzvjkvq74yqjypcwxujpvh4grxp30u33su8s52d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYcEpCcHYwY083b3hOa3pZ
            T3JSTWduK0k0R1dGMG4vTS9kWlFsZWtKSXlJCi9URW1LNDhuN1JsUisxZEhsYi9r
            d0drU3NYbXN6VFkyaHVkUFl6Q3dzWWMKLS0tIGI5dVR1d0ZlcGRQbW9QZ2xNT1dX
            NnJ4TUpmUkJROVJ5VkNsbDVHQUFra28Kz0BOxiatFENSfLg9RWPMdL/9U0fGy7RL
            HU2AHi7PBY4LBBwtRoGXfNrjC7lUzRUk/0xmLaYZfnzt6Arn926QsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-30T01:30:37Z"
    mac: ENC[AES256_GCM,data:8NShfeLynQtc43Q8gOZhuZFg8ShtjO7zGkf/ESTmjqy1TnfX791rrByCbGkkwtNDMqL35epXZfvnOYRUjk+9tf6NZKEG3HkDHsliBuqgD3Dgz+3TC2jDaMBsnkNKhHeXo9OddoX8mtV2WGG9QHn/BYQ6HzURiSpww/+rESBCQF8=,iv:OvEgnes81gpY/8WSFdWPx5YSkMeMVPcbnPd/1zsQoB0=,tag:fbkcnkxVOkTGllS3trcJVA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
