---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app snmp-exporter
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: *app
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: kube-prometheus-stack
      namespace: observability
    - name: external-secrets
      namespace: external-secrets
  values:
    controllers:
      snmp-exporter:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        # initContainers:
        #   init-config:
        #     image: &configSyncImage
        #       repository: ghcr.io/linuxcontainers/alpine
        #       tag: 3
        #     command:
        #       - sh
        #       - -c
        #       - (envsubst < /template/config.yaml > /config/snmp.yaml)
        #     envFrom: &envFrom
        #       - secretRef:
        #           name: snmp-exporter-secret
        #     resources: &configSyncResources
        #       requests:
        #         cpu: 10m
        #         memory: 10Mi
        #       limits:
        #         memory: 128Mi
        containers:
          app:
            image:
              repository: prom/snmp-exporter
              tag: v0.29.0
            args:
              - "--config.file=/config/snmp.yaml"
            envFrom: &envFrom
              - secretRef:
                  name: snmp-exporter-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /-/healthy
                    port: &port 9116
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 128Mi
        pod:
          enableServiceLinks: false
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: *app
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    #### ServiceMonitior configs are pulled from 1Password
    # serviceMonitor:
    #   app:
    #     enabled: true
    #     endpoints:
    #       - interval: 1m
    #         path: /metrics
    #         port: http
    #         scheme: http
    #         scrapeTimeout: 10s
    #     serviceName: snmp-exporter
    persistence:
      config:
        enabled: true
        type: emptyDir
      config-file:
        type: configMap
        name: snmp-configmap
        globalMounts:
          - path: /template/config.yaml
            subPath: config.yaml
            readOnly: true
  valuesFrom:
    - kind: Secret
      name: snmp-exporter-secret
      valuesKey: values.yaml
      optional: false
