---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: snmp-monitoring
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: snmp-monitoring
    meta.helm.sh/release-namespace: monitoring
secrets:
  - name: snmp-monitoring
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: snmp-monitoring
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: snmp-monitoring
    meta.helm.sh/release-namespace: monitoring
    kubernetes.io/service-account.name: snmp-monitoring
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: snmp-exporter
  namespace:
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: snmp-exporter
    meta.helm.sh/release-namespace: monitoring
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: snmp-exporter
  namespace:
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: snmp-exporter
    meta.helm.sh/release-namespace: monitoring
subjects:
- kind: ServiceAccount
  name: snmp-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: snmp-exporter