---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nebula-sync
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: nebula-sync-secret
    template:
      engineVersion: v2
      data:
        PRIMARY: "{{ .PIHOLE_SERVER }}|{{ .PIHOLE_PASSWORD }}"
        REPLICAS: "{{ .NEBULA_REPLICAS }}"
        WEBHOOK_SYNC_SUCCESS_URL: "{{ .NEBULA_WEBHOOK_SYNC_SUCCESS_URL }}"
        WEBHOOK_SYNC_SUCCESS_HEADERS: "{{ .NEBULA_WEBHOOK_TOKEN }}"
        WEBHOOK_SYNC_FAILURE_URL: "{{ .NEBULA_WEBHOOK_SYNC_FAILURE_URL }}"
        WEBHOOK_SYNC_FAILURE_HEADERS: "{{ .NEBULA_WEBHOOK_TOKEN }}"
  dataFrom:
    - extract:
        key: nebula-sync
    - extract:
        key: pihole
