---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linkwarden-cnpg
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: linkwarden-cnpg-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: username
      remoteRef:
        key: linkwarden-cnpg
        property: LINKWARDEN_PG_SUPER_USER
    - secretKey: password
      remoteRef:
        key: linkwarden-cnpg
        property: LINKWARDEN_PG_SUPER_PASS