---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-stack
spec:
  dependsOn:
    - name: openebs
      namespace: openebs-system
  components:
    - ../../../../components/defaults
    - ../../../../components/gatus/webhook
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
      - name: alertmanager-secret
        kind: Secret
    substitute:
      APP: alertmanager
  interval: 1h
  path: ./kubernetes/apps/observability/kube-prometheus-stack/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: observability
  wait: false
