---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gatus
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: gatus-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        INIT_POSTGRES_DBNAME: gatus
        INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .GATUS_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .GATUS_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        CLOUDFLARE_DOMAIN: "{{ .CLOUDFLARE_DOMAIN }}"
        PIHOLE_LOCAL_DNS_IP: "{{ .PIHOLE_LOCAL_DNS_IP }}"
        PUSHOVER_USER_KEY: "{{ .PUSHOVER_USER_KEY }}"
        GATUS_PUSHOVER_TOKEN: "{{ .GATUS_PUSHOVER_TOKEN }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: gatus
    - extract:
        key: cloudflare
    - extract:
        key: pihole
    - extract:
        key: pushover
