---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: orbital-sync
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: orbital-sync-secret
    template:
      engineVersion: v2
      data:
        PRIMARY_HOST_BASE_URL: "{{ .PIHOLE_LOCAL_DNS_IP }}"
        PRIMARY_HOST_PASSWORD: "{{ .PIHOLE_PASSWORD }}"
        SECONDARY_HOSTS_1_BASE_URL: "{{ .ORBITAL_SYNC_PIHOLE_1 }}"
        SECONDARY_HOSTS_1_PASSWORD: "{{ .ORBITAL_SYNC_PIHOLE_1_PASSWORD }}"

  dataFrom:
    - extract:
        key: orbital-sync
    - extract:
        key: pihole