---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./dns/
configMapGenerator:
  - name: gatus-external-service-tpl
    files:
      - gatus-external-service.yaml=./resources/gatus-external-service.yaml
generatorOptions:
  disableNameSuffixHash: true